### ISSUE TITLE
DOCX/PPTX conversion to PDF

### ISSUE THREAD

**Issue by mojtabakaviani** [OfficeDev/Open-Xml-PowerTools#1]
please work on DOCX/PPTX conversion to PDF

**Comment by EricWhiteDev** [comment]
That is a really great idea, but we have some super high-pri projects to do before this comes to the top of the stack.  There are commercial products out there that do this, I believe.  Have you taken a look at them?

**Comment by mojtabakaviani** [comment]
So, Conversion to XPS/OXPS/TIFF
