### ISSUE TITLE
Pivottable data value subtotal is always sum

### ISSUE THREAD

**Issue by TBCarlosPombeiro** [OfficeDev/Open-Xml-PowerTools#106]
The AddDataValue method in WorksheetAccessor class doesn't accept a subtotal function. By default the spreadsheet will use sum.

Changing 
```
fields.Add(new XElement(S.dataField, new XAttribute(NoNamespace.name, "Sum of " + fieldName),
                        new XAttribute(NoNamespace.fld, index), new XAttribute(NoNamespace.baseField, 0),
                        new XAttribute(NoNamespace.baseItem, 0)));
```
to (example)
```
fields.Add(new XElement(S.dataField, new XAttribute(NoNamespace.name, "Sum of " + fieldName),
                        new XAttribute(NoNamespace.fld, index), 
new XAttribute(NoNamespace.subtotal, "count"),
new XAttribute(NoNamespace.baseField, 0),
                        new XAttribute(NoNamespace.baseItem, 0)));
```
 will work?!

**Comment by g-tw0** [comment]
WorksheetAccessor.AddDataValue(doc, pivot, "Column Name", <Summary Type>);

there should have been some argument regarding Summary Type as we can't find a way to change summary type through code and it is taking by default 'SUM'.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
