### ISSUE TITLE
The RemoveRsidInfo option of SimplifyMarkupSettings does not work on Strict Open XML Word documents.

### ISSUE THREAD

**Issue by raphacp** [OfficeDev/Open-Xml-PowerTools#107]
The RemoveRsidInfo option of SimplifyMarkupSettings does not work on Strict Open XML Word documents.
The document.xml file is untouched. No lines in the document.xml file are modified.

**Comment by EricWhiteDev** [comment]
@raphacp yes, you are right.  The Open-Xml-PowerTools have only been tested mainly on transitional documents, although I have used the Open-Xml-Sdk to convert from strict to transitional, and then used the Open-Xml-PowerTools on them.  I suggest you take this approach.  Supporting strict isn't an activity that is currently scheduled, unfortunately.

**Comment by raphacp** [comment]
I followed your suggestion, and converted from strict to transitional, to be able to use the Open-Xml-PowerTools functionality, then back to strict.
I'll be praying, so that one day the Strict Open XML support be placed on the agenda of Open-Xml-PowerTools.
Unfortunately I do not have enough knowledge about XML transformation to update the code. But I suppose it's a matter of Strict Open XML namespaces.
Thank you for your attention.

**Comment by programcsharp** [comment]
How does one "use the Open-Xml-Sdk to convert from strict to transitional"?

I'm using `HtmlConverter.ConvertToHtml` to accept uploaded Word documents to HTML for a CMS. If someone uploads a strict doc, it blows up with a null reference exception down in the entrails of that method. I traced it to the namespace matching in there -- strict docs use a different namespace so it just doesn't know what to do.

I was going to put in an issue for that, but if the conversion is the way to go that will work if I can figure out how to do it.

Still might want a better message on the HtmlConverter if strict isn't supported.
