### ISSUE TITLE
SpreadsheetWriter loses cell formats for second worksheet

### ISSUE THREAD

**Issue by CarlLanglais** [OfficeDev/Open-Xml-PowerTools#109]
I've adapted your example to write out one worksheet with large data to be able to do multiple worksheets from multiple Lists in a List of Lists holder I created and DataTables stored within a DataSet.  The bug I've run into is that if a DataType does not exist on the first Worksheet, then the format style for that DataType does not get saved out to the Styles XML.  

For instance, we default our DateTimes to have a format applied of "mm-dd-yy".  If there is a DateTime in the first List, which writes to the first Worksheet, the x:xf element is added to cellXFS with a FmtID = 14 and the worksheet cell's 's' attribute points to the index.  If DateTime is not in the first List and is in the second List, which writes to worksheets in order, no x:xf element is added to cellXFS but the cell's 's' attribute in the second worksheet will have in index value that is out of range and will display a content error upon first opening the file asking to recover, which removes the bad style attribute from the cells.  

The same issue happens with DataSets also.  If the second DataTable has a DateTime and the first DataTable does not, it loses the style element, but the cell in the worksheet contains an index for the missing style.

This also happens for Decimal, Double and Float which has a format code of "#,##0.#########0".

Below is my DataSet export method example

    
    public static void ExportToExcel(DataSet dataSet, string fileName, string directory)
        {
            //better test than this needed
            foreach (DataTable table in dataSet.Tables)
            {
                if (table.Rows.Count < 1)
                    return;
            }

            WorkbookDfn wb = new WorkbookDfn
            {
                Worksheets = dataSet.Tables
                    .Cast<DataTable>()
                    .Select(d => new WorksheetDfn
                    {
                        Name = d.TableName,
                        ColumnHeadings =
                            d.Columns.Cast<DataColumn>()
                                .Select(c => new CellDfn {Value = c.ToString(), Bold = true}),
                        Rows = d.Rows.Cast<DataRow>().Select(r =>
                            new RowDfn
                            {
                                Cells =
                                    d.Columns.Cast<DataColumn>()
                                        .Select(
                                        z =>
                                            ToExcelType.ReturnCellByDataType(r[z.ColumnName].ToString()
                                            , z.DataType.ToString()))
                            })
                    })
            };
            
            var loc = directory + fileName;

            SpreadsheetWriter.Write(loc, wb);
        }

Also the Return Cell type code that returns a cell with it's datatype and format string.

    public static CellDfn ReturnCellByDataType(string dataValue, string dataType)
        {
            if (dataValue == null)
            {
                return new CellDfn {Value = dataValue, CellDataType = CellDataType.String};
            }
            
            switch (dataType)
            {
                case "System.String":
                    return new CellDfn {Value = dataValue, CellDataType = CellDataType.String};
                case "System.Int16":
                case "System.Int32":
                case "System.Int64":
                case "System.UInt16":
                case "System.UInt32":
                case "System.UInt64":
                case "System.TimeSpan":
                    return new CellDfn {Value = dataValue, CellDataType = CellDataType.Number};

                case "System.Decimal":
                case "System.Double":
                case "System.Single":
                    return new CellDfn
                    {
                        Value = dataValue,
                        CellDataType = CellDataType.Number,
                        FormatCode = "#,##0.#########0"
                    };

                case "System.Boolean":
                    return new CellDfn
                    {
                        Value = dataValue == "True" ? "1" : "0",
                        CellDataType = CellDataType.Boolean
                    };

                case "System.Byte":
                case "System.SByte":
                    return new CellDfn {Value = dataValue, CellDataType = CellDataType.Number};

                case "System.DateTime":
                    return new CellDfn
                    {
                        Value = !string.IsNullOrWhiteSpace(dataValue) ? Convert.ToDateTime(dataValue).ToOADate().ToString() : "",
                        CellDataType = CellDataType.Number,
                        FormatCode = "mm-dd-yy"
                    };

                case "System.Guid":
                    return new CellDfn {Value = dataValue, CellDataType = CellDataType.String};

                default:
                    return (CellDfn) null;
            }
        }

I'm having trouble attaching the files from work pc, so I'll need try from home later.

Updated with example files.

[DsOutHasStyle - Copy.zip](https://github.com/OfficeDev/Open-Xml-PowerTools/files/736339/DsOutHasStyle.-.Copy.zip)
[DsOutHasStyle.XLSX](https://github.com/OfficeDev/Open-Xml-PowerTools/files/736340/DsOutHasStyle.XLSX)
[DsOutStyleMissing - Copy.zip](https://github.com/OfficeDev/Open-Xml-PowerTools/files/736337/DsOutStyleMissing.-.Copy.zip)
[DsOutStyleMissing.XLSX](https://github.com/OfficeDev/Open-Xml-PowerTools/files/736338/DsOutStyleMissing.XLSX)

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
