### ISSUE TITLE
Pull OpenXML library in via NuGet

### ISSUE THREAD

**Issue by twsouthwick** [OfficeDev/Open-Xml-PowerTools#112]
Now that the OpenXML library is available via a NuGet feed, this project can be updated to not require the OpenXML library repo to be side-by-side for building.

**Comment by tarunchopra** [comment]
We have a PR for this one: #113

**Comment by twsouthwick** [comment]
@tarunchopra Next time, if you add the phrase "Fixes #112" it would automatically close the issue when completed.
