### ISSUE TITLE
Stylename not added to paragraphs with list items

### ISSUE THREAD

**Issue by anupamanair** [OfficeDev/Open-Xml-PowerTools#115]
I encountered this issue while converting word documents to HTML.
For paragraphs with list items, the style name attribute is not being added to the object being returned. The default does add the style name.

![image](https://cloud.githubusercontent.com/assets/13037378/23529710/d5e3ad28-ff5b-11e6-86ca-f427522da172.png)

I have created a pull request and pushed my code fix. Pl merge after review.

[https://github.com/anupamanair/Open-Xml-PowerTools](url)

**Comment by anupamanair** [comment]
Document used for above issue -

[Test Document.docx](https://github.com/OfficeDev/Open-Xml-PowerTools/files/815253/Test.Document.docx)

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
