### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by ant-s** [OfficeDev/Open-Xml-PowerTools#116]
I'm coming at this from a Linux background so let me know if I've got this totally wrong, but Open-Xml-SDK now supports .NET Core (https://github.com/OfficeDev/Open-XML-SDK/issues/168) and it would be great if PowerTools did too to allow for it to be run on other platforms. I think this cross-platform adoption is closely aligned with the goals of Open XML being open source.

I ran ApiPortAnalysis and the changes don't look too bad:
[ApiPortAnalysis.xlsx](https://github.com/OfficeDev/Open-Xml-PowerTools/files/819296/ApiPortAnalysis.xlsx)

**Comment by twsouthwick** [comment]
The big ones missing are `System.Drawing` types. Depending how pervasive they are, and what they are used for, it may be doable.

**Comment by EricWhiteDev** [comment]
System.Drawing is used in WmlToHtmlConverter (and a couple of other places IIRC) for getting font metrics.  In my experiments, it was the most accurate for determining font metrics.  I'm sure that there are some sort of capabilities for getting font metrics in COREFX, but I haven't researched it.  In my experience with .NET, there were issues of accuracy with each of the means to get font metrics, so in the end I picked the one where I had to 'hack' it the least.

FYI

**Comment by JoshZA** [comment]
👍

**Comment by cclelio** [comment]
Do you know about the .Net core compatible library "SixLabors" ?
It gives you a TextRenderer class as used in WmlToHtmlConverter.

Do you think it could be doable to use this library to make your own compatible with .net core ?

**Comment by Suriman** [comment]
There are some alternatives that implement System.Drawing and that could be referenced by Open XML PowerTools:

•	https://www.nuget.org/packages/CoreCompat.System.Drawing/1.0.0-beta001
•	https://github.com/JimBobSquarePants/ImageSharp

But ideally, .NET Core will support 100% of the System.Drawing APIs.

**Comment by alexdrl** [comment]
Also, there is a System.Drawing.Common package that will be created, and will be compatible with the existing `System.Drawing` APIs in Windows.

https://github.com/dotnet/corefx/issues/20740

**Comment by ryanlin1986** [comment]
Since .Net Core 2.0 is out,  any update on this?

**Comment by DukeCheng** [comment]
Does any update on this issue? we are expect a .net core porting for PowerTools.

**Comment by ryanlin1986** [comment]
Please do update on this, road blocker for updating to .net Core

**Comment by smbecker** [comment]
Perhaps part of this is splitting out the powershell cmdlets from the pure processing (i.e. `DocumentBuilder`, `DocumentAssembler`) functionality.

**Comment by twsouthwick** [comment]
I chatted with @EricWhiteDev and he wanted to hold off on this until the Powershell stuff is removed. Is there an update for this?

**Comment by EricWhiteDev** [comment]
@twsouthwick No update yet - I will work on getting this done in the next few days.

**Comment by alippai** [comment]
This could help compiling with CoreRT (and later WASM)

**Comment by pholly** [comment]
@EricWhiteDev can we get a quick update on this? Thanks for all your work to provide this library.

**Comment by smbecker** [comment]
I have an initial port based on #148 that takes that one step further with support for `.netstandard2.0`. The existing xunit tests are passing for both `net452` and `netcoreapp2.0`. I'll open a PR once #148 is merged.

https://github.com/smbecker/Open-Xml-PowerTools/tree/netcore

**Comment by ilya-chumakov** [comment]
@smbecker thanks for your fork. I was able to flawlessly compile it after removing the PS-related code (I don't need it anyway). We even have pushed it into our private nuget feed to use `DocumentAssembler` in `netcoreapp2.0`-targeted apps until official PowerTools come.

**Comment by ChrisRyuGS** [comment]
Is there any updates?

**Comment by danieldiazastudillo** [comment]
@smbecker Nice work until official por to NET Core is out. As @ilya-chumakov  i want to use it as a nuget package in my current project, i just need to "clean" XML markup but can you elaborate a little more on how to make ir a nuget package? Thanks in advance

**Comment by twsouthwick** [comment]
@smbecker I got the support for the new project structure merged in yesterday, so any PRs to update to support .netstandard2.0 would be awesome! Incremental ones may be best (not sure how much code churn is required, but just cc me on any PR and I'll take a look at it).

**Comment by tikal** [comment]
Any updates on this ? Thanks

**Comment by ryanlin1986** [comment]
Since .Net Core 2.1 RC was released, any updates on this?

**Comment by NamelessHH** [comment]
I haven't looked at it anymore we went a different way and just used a
different library

**Comment by jacobbutton** [comment]
@NamelessHH What library did you go with?

**Comment by PhenX** [comment]
@twsouthwick I made a PR based on the vNext branch : https://github.com/OfficeDev/Open-Xml-PowerTools/pull/238 

Hope this helps ! 
It supports both netstandard2.0 and net461, all unit tests pass on both targets.

**Comment by axelheer** [comment]
Any updates on this?

**Comment by kwaazaar** [comment]
System.Drawing.Common still only supports running on Windows only. I don't think .NET Core 3 will bring something new to the table, since the desktop support (UWP) will also only be supported on Windows only. Maybe the SixLabors-package is the way to go for netstandard2.0 targetframework, where net461 can remain using System.Drawing.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
