### ISSUE TITLE
PresentationBuilder issue with Telerik Reporting rendered PPTX files

### ISSUE THREAD

**Issue by Lfwinster** [OfficeDev/Open-Xml-PowerTools#117]
When merging pptx files rendered from telerik reporting framework

slide.SlideLayoutPart.GetXDocument().Root.Element(P.cSld).Attribute(NoNamespace.name).Value will return null reference exception.

The pptx file itself only has on blank layout in master slide called Telerik Theme.

I don't know open xml too well but breaking the 
foreach (SlideLayoutPart layoutPart in currentMasterPart.SlideLayoutParts)
if layoutPart.GetXDocument().Root.Element(P.cSld).Attribute(NoNamespace.name) = null
 fixed the issue for my case

Hope this can be resolved in the next release.

**Comment by tomjebo** [comment]
@Lfwinster please feel free to implement the fix on your branch, test and submit a PR.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
