### ISSUE TITLE
After calling DocumentBuilder.BuildDocument Empty Headers/footers change spacing of document.

### ISSUE THREAD

**Issue by catsgotmytongue** [OfficeDev/Open-Xml-PowerTools#119]
When building a set of sources with DocumentBuilder the headers and footers added are essentially empty paragraphs that change the spacing of the final document in the header or footer by having additional line breaks in what the end user sees.

I think there should be additional ways to add/update headers or footers in the DocumentBuilder.

My suggestion would be to have an overload for markup to be passed in that represents default header/footer content when none are found for that source.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
