### ISSUE TITLE
Could not load file or assembly 'System.IO.Packaging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by jmhmaine** [OfficeDev/Open-Xml-PowerTools#121]
If you upgrade the OpenXMLSDK-MOT dependency from version 2.6.0 to 2.6.1, the following runtime error is thrown:

> Could not load file or assembly 'System.IO.Packaging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

Also, it appears that the OpenXMLSDK-MOT dependency has moved to MyGet and is on version 2.7.1:
https://dotnet.myget.org/feed/open-xml-sdk/package/nuget/DocumentFormat.OpenXml/2.7.1

Are there plans to update to update to support OpenXMLSDK-MOT version 2.6.1 or using the MyGet version?

**Comment by jeffklawiter** [comment]
I have also run into this, ended up reverting back to 2.6.0.

**Comment by linxkulit** [comment]
This project requires to sign the project with certificate (.snk or .key) on build.
Also the stable v.4.5.3.1 need to match the assembly version on build, as it reflects the old v.4.5.3.0.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
