### ISSUE TITLE
Unable to run any PowerShell Cmdlets

### ISSUE THREAD

**Issue by MatthewMcD** [OfficeDev/Open-Xml-PowerTools#143]
I am really struggling here.
I cloned both Open-XML-SDK and Open-XML-PowerTools.
I compiled the Open-XML-SDK
I tried 
`Import-Module .\Open-XML-PowerTools.psm1` and I get:
> Add-Type : Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path 'C:\Users\ruby\Documents\WindowsPowerShell\Modules\Open-Xml-Sdk\DocumentFormat.OpenXml\bin\debug\System.IO.Packaging.dll' because it does not exist."
> At C:\Users\ruby\Documents\WindowsPowerShell\Modules\Open-Xml-PowerTools\AddTypes.ps1:69 char:16. -Type -Path "$PSScriptRoot\..\Open-Xml-Sdk\DocumentFormat.OpenXml\bin ...
> CategoryInfo          : WriteError: (:) [Add-Type], ParameterBindingException
> FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.PowerShell.Commands.AddTypeCommand
> 
> Add-Type : (0) : Metadata file 'C:\Users\ruby\Documents\WindowsPowerShell\Modules\Open-Xml-PowerTools\..\Open-Xml-Sdk\DocumentFormat.OpenXml\bin\debug\System.IO.Packaging.dll' could not be found
> At C:\Users\ruby\Documents\WindowsPowerShell\Modules\Open-Xml-PowerTools\AddTypes.ps1:70 char:1
> Add-Type -ReferencedAssemblies $assemblies -Path $sources -OutputAsse ...
>  CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type], Exception FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand
> Add-Type : Cannot add type. Compilation errors occurred.
> At C:\Users\ruby\Documents\WindowsPowerShell\Modules\Open-Xml-PowerTools\AddTypes.ps1:70 char:1
> Add-Type -ReferencedAssemblies $assemblies -Path $sources -OutputAsse ...
>  CategoryInfo          : InvalidData: (:) [Add-Type], InvalidOperationException
> FullyQualifiedErrorId : COMPILER_ERRORS,Microsoft.PowerShell.Commands.AddTypeCommand

I fixed the paths by adding "\net46\ to the debug dll locations in AddTypes.ps1 Now the Import-Module works without error. When I try any cmdlet like the example:
`New-Docx Out-2.docx -Comment`
I get:

> New-Object : Cannot find type [System.Collections.Generic.List[OpenXmlPowerTools.Source]]: verify that the assembly containing this type is loaded.
> At C:\Users\ruby\Documents\WindowsPowerShell\Modules\Open-Xml-PowerTools\Cmdlets\New-Docx.ps1:303 char:16   $srcList = New-Object 'System.Collections.Generic.List[OpenXmlPowerT ...
> CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
> FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand
> 
> New-Object : Cannot find type [OpenXmlPowerTools.WmlDocument]: verify that the assembly containing this type is loaded. At C:\Users\ruby\Documents\WindowsPowerShell\Modules\Open-Xml-PowerTools\Cmdlets\New-Docx.ps1:404 char:13
> $wml = (New-Object OpenXmlPowerTools.WmlDocument("DummyName.docx" ...
> CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
> FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand
> 
> New-Object : Cannot find type [OpenXmlPowerTools.Source]: verify that the assembly containing this type is loaded. At C:\Users\ruby\Documents\WindowsPowerShell\Modules\Open-Xml-PowerTools\Cmdlets\New-Docx.ps1:411 char:17
> $src = (New-Object OpenXmlPowerTools.Source($wml))
> CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
> FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand
> 
> You cannot call a method on a null-valued expression.
> At C:\Users\ruby\Documents\WindowsPowerShell\Modules\Open-Xml-PowerTools\Cmdlets\New-Docx.ps1:413 char:5
> $srcList.Add($src)
> 
> CategoryInfo          : InvalidOperation: (:) [], RuntimeException
> FullyQualifiedErrorId : InvokeMethodOnNull
> 
> Unable to find type [OpenXmlPowerTools.DocumentBuilder]. At C:\Users\ruby\Documents\WindowsPowerShell\Modules\Open-Xml-PowerTools\Cmdlets\New-Docx.ps1:351 char:26
> $mergedWmlDocument = [OpenXmlPowerTools.DocumentBuilder]::BuildDo ...
> CategoryInfo          : InvalidOperation: (OpenXmlPowerTools.DocumentBuilder:TypeName) [], RuntimeException FullyQualifiedErrorId : TypeNotFound
> 
> You cannot call a method on a null-valued expression.
> At C:\Users\ruby\Documents\WindowsPowerShell\Modules\Open-Xml-PowerTools\Cmdlets\New-Docx.ps1:385 char:13
> $mergedWmlDocument.SaveAs($outputFi.FullName)
> CategoryInfo          : InvalidOperation: (:) [], RuntimeException
> FullyQualifiedErrorId : InvokeMethodOnNull
> 

Does the PowerShell work for anyone? I just want to use the project. I have spent several hours on and off trying to get this to work. Any help will be greatly appreciated.

Even better...can I get an "Install-Module" option so I don't have to build it all myself?

**Comment by MatthewMcD** [comment]
Fixed another path issue and now when trying to import the module I get:

> Add-Type :
> c:\Users\ruby\Documents\WindowsPowerShell\Modules\Open-Xml-PowerTools\OpenXmlPowerTools\PtOpenXmlDocument.cs(540) :
> The type name 'Package' could not be found. This type has been forwarded to assembly 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Consider adding a reference to that assembly. 
> c:\Users\ruby\Documents\WindowsPowerShell\Modules\Open-Xml-PowerTools\OpenXmlPowerTools\PtOpenXmlDocument.cs(539) :
> private MemoryStream DocMemoryStream;
> c:\Users\ruby\Documents\WindowsPowerShell\Modules\Open-Xml-PowerTools\OpenXmlPowerTools\PtOpenXmlDocument.cs(540) :
> private Package DocPackage;
> c:\Users\ruby\Documents\WindowsPowerShell\Modules\Open-Xml-PowerTools\OpenXmlPowerTools\PtOpenXmlDocument.cs(541) :
> At C:\Users\ruby\Documents\WindowsPowerShell\Modules\Open-Xml-PowerTools\AddTypes.ps1:70 char:1
> Add-Type -ReferencedAssemblies $assemblies -Path $sources -OutputAsse ...
> CategoryInfo  : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type], Exception
> FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand
>

**Comment by lrchma** [comment]
I had the same error but using the below command resolved it (Package is part of WindowsBase)

[System.Reflection.Assembly]::LoadFrom("C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\WindowsBase.dll")

Best Regards,

Chris

**Comment by MatthewMcD** [comment]
The Import-Module works, but when I try:
`new-docx -OutputPath "c:\users\ruby\documents\test.docx" -Empty`

> New-Object : Cannot find type [System.Collections.Generic.List[OpenXmlPowerTools.Source]]: verify that the assembly cont
> At C:\Users\ruby\Documents\WindowsPowerShell\Modules\Open-Xml-PowerTools\Cmdlets\New-Docx.ps1:303 char:16
> ...  $srcList = New-Object 'System.Collections.Generic.List[OpenXmlPowerT ...
>                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
>      FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand
> 
> New-Object : Cannot find type [OpenXmlPowerTools.WmlDocument]: verify that the assembly containing this type is loaded.
> At C:\Users\ruby\Documents\WindowsPowerShell\Modules\Open-Xml-PowerTools\Cmdlets\New-Docx.ps1:404 char:13
>      $wml = (New-Object OpenXmlPowerTools.WmlDocument("DummyName.docx" ...
>              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
>      FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand
> 
> New-Object : Cannot find type [OpenXmlPowerTools.Source]: verify that the assembly containing this type is loaded.
> At C:\Users\ruby\Documents\WindowsPowerShell\Modules\Open-Xml-PowerTools\Cmdlets\New-Docx.ps1:411 char:17
>          $src = (New-Object OpenXmlPowerTools.Source($wml))
>                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
>      FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand
> 
> You cannot call a method on a null-valued expression.
> At C:\Users\ruby\Documents\WindowsPowerShell\Modules\Open-Xml-PowerTools\Cmdlets\New-Docx.ps1:413 char:5
>      $srcList.Add($src)
>      ~~~~~~~~~~~~~~~~~~
>      CategoryInfo          : InvalidOperation: (:) [], RuntimeException
>      FullyQualifiedErrorId : InvokeMethodOnNull
> 
> Unable to find type [OpenXmlPowerTools.DocumentBuilder].
> At C:\Users\ruby\Documents\WindowsPowerShell\Modules\Open-Xml-PowerTools\Cmdlets\New-Docx.ps1:351 char:26
>      $mergedWmlDocument = [OpenXmlPowerTools.DocumentBuilder]::BuildDo ...
>                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      CategoryInfo          : InvalidOperation: (OpenXmlPowerTools.DocumentBuilder:TypeName) [], RuntimeException
>      FullyQualifiedErrorId : TypeNotFound
> 
> You cannot call a method on a null-valued expression.
> At C:\Users\ruby\Documents\WindowsPowerShell\Modules\Open-Xml-PowerTools\Cmdlets\New-Docx.ps1:385 char:13
>              $mergedWmlDocument.SaveAs($outputFi.FullName)
>              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      CategoryInfo          : InvalidOperation: (:) [], RuntimeException
>      FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by benbro** [comment]
Maybe this PR helps
https://github.com/OfficeDev/Open-Xml-PowerTools/pull/180
