### ISSUE TITLE
Converting list from HTML to WML problem

### ISSUE THREAD

**Issue by MrMilo** [OfficeDev/Open-Xml-PowerTools#144]
When I try to convert a list like:

```
<ol>
<li>testing</li>
<li>testing again
<ul>
<li>bullet 1</li>
<li>bullet 2</li>
</ul>
```

it's suppose to show number then bullet, but after export it show number for both first level and second level, what's the problem here?

P/S: using PowerTools 4.5.3.1, and `ConvertHtmlToWml` , the code I use to convert is exactly the same as per example

**Comment by MrSaints** [comment]
You're missing some closing tags, i.e. `</li>`, and `</ol>`

**Comment by MrMilo** [comment]
@MrSaints just noticed there's a typo, the actual code that I used to convert is:

```
<ol>
	<li>testing</li>
	<li>testing again
		<ul>
			<li>bullet 1</li>
			<li>bullet 2</li>
		</ul>
	</li>
</ol>
```

It render correctly when I export a list where first level are <ul> and second level are <ol> though.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
