### ISSUE TITLE
Problem copying charts

### ISSUE THREAD

**Issue by denza** [OfficeDev/Open-Xml-PowerTools#149]
[Method CopyChartObjects](https://github.com/OfficeDev/Open-Xml-PowerTools/blob/vNext/OpenXmlPowerTools/DocumentBuilder.cs#L1962) in DocumentBuilder is expecting EmbeddedPackagePart, which is for most of the time working as expected. I have docx file with chart of type EmbeddedObjectPart.

I am not sure is it error since there is code above copy chart area which handles O.OLEObject.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
