### ISSUE TITLE
Appveyor builds

### ISSUE THREAD

**Issue by daniel-white** [OfficeDev/Open-Xml-PowerTools#154]
Hi.

I'm trying to build using AppVeyor in our fork. `vNext` seems to have a problem resolving the Nuget package for the vNext of the SDK. `master` seems to be attempting to use the latest sdk but fails to find `System.IO.Packaging`. Any guidance would be appreciated.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
