### ISSUE TITLE
Bug in UnicodeMapper

### ISSUE THREAD

**Issue by ajan1966** [OfficeDev/Open-Xml-PowerTools#155]
Line 78 
`.Where(e => StringifiedRunElements.Contains(e.Name))`
should be changed to 
` .Where(e => e.Name != W.rPr)`
because as it is, only the Elements in StringifiedRunElements are handled, an the other elements are ignored (and not transferred into  U+0001. That leads to difference in String vs. Runs, so that the text gets replaced at incorrect position.

**Comment by ThomasBarnekow** [comment]
@ajan1966 Could you check whether that has been fixed in the latest version?

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
