### ISSUE TITLE
PowerToolsBlockExtensions.BeginPowerToolsBlock calls nonexistent Save method

### ISSUE THREAD

**Issue by daniel-white** [OfficeDev/Open-Xml-PowerTools#156]
I'm trying to understand where the `Save` method is coming from off of `OpenXmlPackage`. Its been commented out in the SDK repo.

https://github.com/OfficeDev/Open-XML-SDK/blob/vNext/DocumentFormat.OpenXml/src/Framework/OpenXmlPackage.cs#L555

When I comment out the call to `Save`, it fails a bunch of tests.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
