### ISSUE TITLE
DocumentBuilder: Merge documents with header section

### ISSUE THREAD

**Issue by juanperezADD** [OfficeDev/Open-Xml-PowerTools#157]
We have a technical question about merging documents. We want to combine multiple documents, each one with a different header, in one document with a header that is a merge of the others documents.

Here is an example:

-	Company document: This is a document that we want to reuse in multiple documents. It contains in its header the company name and common information.

-	Report document: This document includes in its header the Company document and additional information like the title of the report and parameters to filter the data to display.
 
-	Final document: The final result should be one document that contains the company and report information in the header section.

Currently, we have tried to do this example using DocumentBuilder and at the final document there is only one of the headers, instead of a merge of all. Is it possible to combine headers with DocumentBuilder? Is there any technical limitation?

**Comment by dkarnati** [comment]
I am trying the same. I have achieved it by  using "DiscardHeadersAndFootersInKeptSections". I am setting this to false. It works great. 

            foreach (var stream in documentstreams)
            {
                // var tempms = new MemoryStream();
                // stream.CopyTo(tempms);
                OpenXmlPowerTools.Source sc = new OpenXmlPowerTools.Source(new WmlDocument(stream.Length.ToString(), stream), true);
                sc.DiscardHeadersAndFootersInKeptSections = false;
                // sc.
                sources.Add(sc);
            }

**Comment by VictorIranzo** [comment]
The above solution doesn't work for me. I think we have the same problem as @juanperezADD : how can I merge 2 documents in the header of a single document? The information that I want to show in the final header can come in the body or the header (the easiest way) of the source documents and it can have images. If this it's not possible with DocumentBuilder, is there any DocumentAssembler notation to do that in a simple way?

**Comment by EricWhiteDev** [comment]
I am currently working on an enhancement to enable DocumentBuilder to insert documents into headers, using the approach whereby you insert a special bit of markup where you want the document to be inserted in the header.  You can then merge two documents into a header.

See screen-cast #6 in this list:

http://ericwhite.com/blog/blog/documentbuilder-developer-center/

**Comment by VictorIranzo** [comment]
I have tried your enhancement. I have a doubt in this situation: 
First, I have a document with a header. Then, I have a document with a body and a header, where the header contains an insert markup that refers to the first document. Could I insert the header of the first document in the place of this markup and keep the rest of the header of the second document?
Right now I'm able to replace the markup in the header with the body of other document, but what I'm looking for is to  replace the markup in the header with the header in other document.

**Comment by EricWhiteDev** [comment]
@VictorIranzo Currently, this is not a feature of DocumentBuilder.  It only supports inserting the body of another document into the header.  It does not support replacing the markup in the header with the header in the other document.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
