### ISSUE TITLE
DocumentBuilder: ImagePart is multiplied which results in potentially massive document

### ISSUE THREAD

**Issue by koyote** [OfficeDev/Open-Xml-PowerTools#159]
Hi,

This is a simple bug to reproduce:

1. Create a document and insert a picture (I like the penguin one in the 'Sample Pictures' folder :))
3. Copy/Paste this picture several dozen times in the same document.
4. Save document as "TheDocument.docx". The document should be just slightly larger than the picture.
5. Run the following code:

```
var source = new Source(new WmlDocument("TheDocument.docx"));
DocumentBuilder.BuildDocument(new List<Source> { source }, "TheOutput.docx");
```

6. TheOutput.docx will be as many times larger than the original document as the amount of times you copy pasted the picture.

What is happening is that essentially the DocumentBuilder copies the ImagePart each time an image relationship is found, even if that relationship id is pointing towards the same image.

**Comment by koyote** [comment]
As a potential fix I found the following:

```       
private static ImageData ManageImageCopy(ImagePart oldImage, OpenXmlPart newContentPart, List<ImageData> images)
        {
            ImageData oldImageData = new ImageData(oldImage);
            foreach (ImageData item in images)
            {
                if (newContentPart != item.ImagePart)
                    continue;
                if (item.Compare(oldImageData))
                    return item;
            }
            images.Add(oldImageData);
            return oldImageData;
        }
```

If you comment out:
```               
 if (newContentPart != item.ImagePart)
                    continue;
```
It works fine.

I am not sure what the original purpose of that line is (in the case above it is comparing the MainDocumentPart to the ImagePart, so always true) so have not filed a pull request.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
