### ISSUE TITLE
vnext branch Path issue + System.IO.Packaging.dll 

### ISSUE THREAD

**Issue by svhadar** [OfficeDev/Open-Xml-PowerTools#161]
Hi,
it is the first time I tried to work with the Open-XML-Powertools.
I cloned the vnext branch and followed the "new" youtube video for the VS2071 build process.
The build process (using OpenXMLPowertools -> targeting .net 4.5)  runs fine with 2 successfull builds and no errors.
While importing the module I run into the following error multiple times:

```
Add-Type : Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path '<path>\WindowsPowerShell\Modules\Open-Xml-Sdk\DocumentFormat.OpenXml\bin\debug\DocumentFormat.OpenXml.dll' because it
does not exist."

```
The "Open-Xml-Sdk" directory does not exist. I assume that this was the path when the Open-XML-SDK was build from source.
As the vnext branch uses nuget the path to the DocumentFormat.OpenXml.dll (to my understanding) should now be:
....\packages\DocumentFormat.OpenXml.2.7.2-vnext0027\lib\net45

Once I changed that in AddTypes.ps1 I get the following while trying to import the module:

```
Add-Type : Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path ```
'<path>\Documents\WindowsPowerShell\Modules\Open-Xml-Sdk\DocumentFormat.OpenXml\bin\debug\System.IO.Packaging.dll' because it
does not exist."
```
The System.IO.Packaging.dll is not included in the open-xml-powertools directory before or after the build.
I tried to install System.IO.Packaging.dll via nuget but it failed due to the targeting  .NET framework (4.5).
I could not find System.IO.Packaging.dll anywhere on my system.

I am working on a windows server 2012 R2 with Powershell 5.
.NET 3.5 and 4.5 are installed.

Can anyone help me out on this?

Thanks

Sven

**Comment by pigrew** [comment]
It seems that the reference is not necessary, and should be removed (at least in .net 4.5). Perhaps the System.IO.Packaging class is made its own DLL in newer versions of .net? The System.IO.Packaging namespace is actually contained within "WindowsBase", which is already references. While building it, I removed all of the references to System.IO.Packaging, and it built cleanly.

**Comment by svhadar** [comment]
Thanks pigrew.

Just to be clear, I am getting a clean build with System.IO.Packaging in the source files, 
The errors I mentioned in my first post occurred while trying to import the Open-XML-Powertools module in a Powershell "session".

I now got a clean clone of Open-XML-Powertools and replaced all occurrences (5) of "using System.IO.Packaging;" with "//using System.IO.Packaging;".
But during the build I now get 7 Errors all related to missing types or namespaces:
They all look like this:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'PackagePart' could not be found (are you missing a using directive or an assembly reference?)	OpenXmlPowerTools	C:\Users\HadarS\Documents\Open-XML-Powertools\OpenXmlPowerTools\WmlComparer.cs	4451	Active
```
only the missing type of namespace varies:
WmlDocument, PackagePart, Package

I may be missing something and would be very grateful is someone can point me in the right direction.

Thanks
Sven

**Comment by ManiMaranVasan** [comment]
i faced the same issue in my project.
i am using .Net framework 3.5 
even i got the error, after included like this 

`using System.IO.Packaging;`


Solution which helped for me is
i have added **WindowsBase** as reference in project which already exist in .Net framework.

Thanks
Maran

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
