### ISSUE TITLE
Invalid XPath expressions caused by MS Word special characters

### ISSUE THREAD

**Issue by johnholliday** [OfficeDev/Open-Xml-PowerTools#162]
Certain XPath expressions will fail if Word special characters such as smart quotes are passed through to XElement methods.  For example, the following table selector will fail because the single quotes are converted to \u2019 by Word and are then passed through to XElement.XPathSelectElements() by DocumentAssembler, which then throws an exception:

`<Table Select="//Order[@Type='X']"`

To fix this, whenever an attribute is extracted from an element, it should be normalized.  I created the following extension method to handle this:

`public static string NormalizeMSWordCharacters(this string s)
{
             var sb = new StringBuilder(s);
             sb.Replace ('\u2018', '\'')
                .Replace ('\u2019', '\'')
                .Replace ('\u2013', '-')
                .Replace ('\u2014', '-')
                .Replace ('\u2015', '-')
                .Replace ('\u2017', '_')
                .Replace ('\u2018', '\'')
                .Replace ('\u2019', '\'')
                .Replace ('\u201a', ',')
                .Replace ('\u201b', '\'')
                .Replace ('\u201c', '\"')
                .Replace ('\u201d', '\"')
                .Replace ('\u201e', '\"')
                .Replace ("\u2026", "...")
                .Replace ('\u2032', '\'')
                .Replace ('\u2033', '\"')
                ;
            return sb.ToString ();   
}
`

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
