### ISSUE TITLE
Symbols/Special characters not recognized

### ISSUE THREAD

**Issue by sucalavlad** [OfficeDev/Open-Xml-PowerTools#164]
Hello. I am using Open-Xml-PowerTools to convert word files to html and back.
The issue I am experiencing is that some of the special characters/symbols like 'less or equal' and 'greater or equal' are being converted to simple equal.
Do you have any ideas on this?

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
