### ISSUE TITLE
Superscript create new lines

### ISSUE THREAD

**Issue by C1rdec** [OfficeDev/Open-Xml-PowerTools#165]
Hi, 
I have issue when I convert a docx to html.
When the docx contains a [Superlink](https://support.office.com/en-us/article/Format-text-as-superscript-or-subscript-e989637a-12ec-4fe5-8b04-345342408abd) the layout is screwed.
# **Docx Input**
`Hi I’m the 1st  and this should be on the same line.` (st is a superscript in the docx)

# **Html Output**
```
Hi I’m the   1  
          st
            and this should be on the same line.
```

Files for the issue [(Issue 165.zip)](https://github.com/OfficeDev/Open-Xml-PowerTools/files/1184029/Issue.165.zip)

I found the culprit! 
`span { white-space: pre-wrap; }`

Is there a way to work around this issue ?

**Comment by C1rdec** [comment]
[TestSuperScript.docx](https://github.com/OfficeDev/Open-Xml-PowerTools/files/1184022/TestSuperScript.docx)

**Comment by C1rdec** [comment]
Here are the files for the issue
[Issue 165.zip](https://github.com/OfficeDev/Open-Xml-PowerTools/files/1184026/Issue.165.zip)

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
