### ISSUE TITLE
Converting html tables to Wml can create invalid documents (according to Word)

### ISSUE THREAD

**Issue by Zache** [OfficeDev/Open-Xml-PowerTools#166]
```html
<table>
<tr>
    <th>The other headers are empty, which is a problem</th>
    <th></th>
    <th></th>
</tr>
<tr>
    <td></td>
    <td><strong></strong></td>
    <td>Empty td-elements work out fine, but not if they contain tags other than p or span</td>
</tr>
<table>
```

Converting this creates wml code that looks like this:
```
snip...
<w:tbl>
<table-stuff />
<w:tr>
<w:trPr></w:trPr>
<w:tc>
    <w:tcPr></w:tcPr>
    <w:p>
        <content further down>
            The other headers are empty, which is a problem
        </content further down>
    </w:p>
    </w:tc>
    <w:tc>
        <w:tcPr></w:tcPr>
    </w:tc>
    <w:tc>
        <w:tcPr></w:tcPr>
    </w:tc>
</w:tr>
<w:tr>
    <w:trPr></w:trPr>
    <w:tc>
        <w:tcPr></w:tcPr>
        <w:p>
            <a bunch of stuff that just wrap an empty string />
        </w:p>
    </w:tc>
    <w:tc>
        <w:tcPr></w:tcPr>
    </w:tc>
    <w:tc>
        <w:tcPr></w:tcPr>
       <w:p>
            <content further down>
                Empty td-elements work out fine, but not if they contain tags other than p or span
            </content further down>
        </w:p>
    </w:tc>
</w:tr>
</w:tbl>
...snip
```
And word doesn't think the resulting wml is valid. It requires `<w:p>` tag to come before the closing `</w:tc>` or in other words: a table cell with just table cell properties is invalid, it also requires some content.
HtmlToWmlConverterCore has a special case that handles this for `<td>` without text, but that doesn't work  if they contain elements other than `p` or `span`.

I tried adding some test cases, but they pass because  according to Open-Xml-Sdk this is still valid wml. According to wml.xsd a table-cell should conform to this schema:
```xsd
<xsd:complexType name="CT_Tc">
    <xsd:sequence>
        <xsd:element name="tcPr" type="CT_TcPr" minOccurs="1" maxOccurs="1"/>
        <xsd:group ref="EG_BlockLevelElts" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
</xsd:complexType>
```
This is what EG_BlockLevelElts looks like:
```xsd
<xsd:group name="EG_BlockLevelElts">
    <xsd:choice>
        <xsd:group ref="EG_BlockLevelChunkElts" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:choice>
</xsd:group>
```
Apparently the `minOccurs="0"` on EG_BlockLevelElts overrides the requirement of `minOccurs="1"` from `CT_tc`, although I don't agree with that interpretation (and neither does Word).

Still I would like to generate documents that are valid for the most common ooxml implementation by far. Currently I can work around this by changing the HTML fed into the converter, but it would be nice to have this handled for me. 

I would like to implement this and submit a pull request, but I wan't to make sure that the changes would be welcome first.

**Comment by Zache** [comment]
I found a related issue here https://github.com/OfficeDev/Open-XML-SDK/issues/8

**Comment by Zache** [comment]
@ThomasBarnekow @EricWhiteDev Could this please get some attention?

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
