### ISSUE TITLE
SpreadsheetWriter outputs the wrong cell type for strings

### ISSUE THREAD

**Issue by pigrew** [OfficeDev/Open-Xml-PowerTools#168]
Based on the ECMA standard, the "str" cell type should only be used for formula strings.

However, the SpreadsheetWriter class uses "str" for all strings. 

Instead, it should either use an inline-string ("inlineStr"), or a shared-string ("s"). (Excel seems to use shared-strings most often)

For the inline-string, the text should be inside of inlineString/text markup.

See <https://stackoverflow.com/questions/6468783/what-is-the-difference-between-cellvalues-inlinestring-and-cellvalues-string-in>.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
