### ISSUE TITLE
Help with Hyperlinks in an Excel sheet's cell not working.

### ISSUE THREAD

**Issue by NETESudarshan** [OfficeDev/Open-Xml-PowerTools#169]
Hello - 

We are trying to include hyperlinks in spread sheets that we download from our web sites.
The OpenXMLPowerTools works great, except we are unable to figure out an inbuilt way of writing a hyperlink to a cell.
As a work around, we tried using the formula "=HYPERLINK(""http://example.com"") for the cell value.
However, when the file is downloaded, the cell value shows as is like ```=HYPERLINK("http://example.com")```, instead of a http://example.com. 
Only when we double click on the cell, the value gets evaluated and shows as a hyperlink.

Any help, will be appreciated, thanks.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
