### ISSUE TITLE
Be able to Slide Size during creation

### ISSUE THREAD

**Issue by ranjithvenkatesh** [OfficeDev/Open-Xml-PowerTools#170]
I am using the PresentationBuilder to create a PowerPoint presentation which takes multiple PowerPoint sources. The Slide Size is based on the first source document.

It would be great to set the slide size for the entire document irrespective of the individual sources.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
