### ISSUE TITLE
It does not convert math formulas, SmartArt, or DrawingML drawings.

### ISSUE THREAD

**Issue by fanbeisinan** [OfficeDev/Open-Xml-PowerTools#171]
It does not convert math formulas, SmartArt, or DrawingML drawings.
它不能转换数学公式、SmartArt 或 DrawingML 绘图。

**Comment by nlsdg** [comment]
Can you specify in more detail from what or to what you want to convert them?

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
