### ISSUE TITLE
Normalization of some table cell structures loses formatting

### ISSUE THREAD

**Issue by sixlettervariables** [OfficeDev/Open-Xml-PowerTools#172]
The code in DocumentAssembler that normalizes table cells and content controls loses cell formatting:

https://github.com/OfficeDev/Open-Xml-PowerTools/blob/473a21a09d6b690e81cf24a0d0cbe1d11cb36000/OpenXmlPowerTools/DocumentAssembler.cs#L195

It needs to reference the `W.sdtContent` element before the `W.tc` elements.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
