### ISSUE TITLE
Issues when converting links with HtmlToWmlConverter

### ISSUE THREAD

**Issue by lajjne** [OfficeDev/Open-Xml-PowerTools#18]
I found a couple of issues with converting `<a href=""></a>` links to Wml.

If the href attribute does not exist or is not a valid Uri the link text is removed from the converted document. In my opinion it would be better to keep the link text: Example

`Testing <a href="#">link</a> with #` => `Testing with #`

Linked images are removed from the output. Example

`An image <a href="http://www.example.com"><img src="/img/image.png" alt="" /></a>` => `An image`

Link in table cell generates invalid word document. Example: 

`<table><tr><td><a href="http://www.example.com">example</a></td></tr></table>`

**Comment by EricWhiteDev** [comment]
I agree with this.  Needs to be addressed.  I have assigned to myself.

**Comment by EricWhiteDev** [comment]
@lajjne I've made these modifications:

- links with invalid URIs have their contents generated.
- linked images are properly processed.
- link in table cell now generates correct markup.

Have added Xunit tests.

These changes are in the vNext branch in the repo.
