### ISSUE TITLE
DocumentAssembler - binding directives in tables

### ISSUE THREAD

**Issue by mesteves** [OfficeDev/Open-Xml-PowerTools#184]
Hi,

I'm trying to use DocumentAssembler to generate documents based on xml files, and using repeat directive associated with table directive, i'm not being able to:

1. Use two expressions in one cell of the prototype row (like ./Price ./CurrencySymbol )
2. Use select content expression on table header. (like **Price** `<# <Content Select="./SaleItems/SaleItem[1]/@Currency"/> #>` ) - produces invalid document

Any help on this would be appreciated,

Best regards,
Manuel

**Comment by EricWhiteDev** [comment]
Hi Manuel,

DocumentAssembler doesn't have a fair number of options for combining / pulling data from XML files -

Instead, I envision using this by generating exactly the XML that you want, and then DocumentAssembler does the hard work of integrating that data into the DOCX.  So if you want both price and currency symbol in a table header, put them in the XML data file in that way.

I know that this isn't ideal, but I hesitated to make it too complex.

Regards, Eric

**Comment by mesteves** [comment]
Hi Eric, 

Yes, I understand and agree, and like you suggested I thought in that solution, and that works perfectly.

However, one thing that would be very useful, is allow content selector tags on the table header. I've played arround a bit and is only allowing to add on prototype row (`./ItemPrice`) and on some footer rows syntax like (`<# <Content Select="./SaleItems/SaleItem[1]/CurrencySymbol"/> #>`)

![image](https://user-images.githubusercontent.com/3369185/30719545-d20aaa8e-9f1b-11e7-8656-ed254b884f5e.png)

The item marked in red doesn't work and produces invalid document.

Is there a way for this ?

Thanks Eric !

Kind regards,
Manuel

**Comment by MalcolmJohnston** [comment]
Hello Manuel, 

I believe that there is a way that you can achieve this by splitting the table and using the <Repeat> construct instead of the <Table> construct.

Please see my example below and see what you think.

![image](https://user-images.githubusercontent.com/33666206/34780613-7fc979ec-f61b-11e7-9ec2-7801af59f5ee.png)

I would normally wrap this whole block in a conditional like;

<# <Conditional Select="count(./SaleItems/SaleItem) > 0" Match="True" /> #>

Cheers,
Malcolm

**Comment by mesteves** [comment]
Thanks @MalcolmJohnston that is a good way to workarround!! :)

Thank you!

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
