### ISSUE TITLE
DocumentAssembler - vNext line 558 - p.Elements().Count()

### ISSUE THREAD

**Issue by ben-demotic** [OfficeDev/Open-Xml-PowerTools#185]
Hi Eric

Thanks for the great library.  I just discovered OpenXmlPowerTools recently and am using it to replace my old RTF based token replacement with DOCX to really save on those storage costs!

Anyway, while working with some multi-line address data, delimited by '\n', I had a problem whereby not all of the <br/> elements were being inserted.

For example, say I have this text:

17 Shire Oak Road\nSaxlingham\nNR15 5TR

I have 2 documents where I am attempting to insert this data formatted with new lines as an address.  The first document, the token is replaced by the following which correctly contains a <br/> inserted before the 2nd and 3rd elements:

```
<?xml version="1.0"?>
   <p xmlns="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
      <pPr>
         <pStyle xmlns:p3="http://schemas.openxmlformats.org/wordprocessingml/2006/main" 
              p3:val="NoSpacing"/>
         <rPr>
            <bCs/>
         </rPr>
      </pPr>
      <r>
         <rPr>
            <bCs/>
         </rPr>
         <t>17 Shire Oak Road</t>
      </r>
      <r>
         <rPr>
            <bCs/>
         </rPr>
         <br/>
         <t>Saxlingham</t>
      </r>
      <r>
         <rPr>
            <bCs/>
         </rPr>
         <br/>
         <t>NR15 5TR</t>
      </r>
   </p>
```
The second document does not have the extra <rPr><bCs/><rPr> of the first and if you look you can see that it has not put the <br/> before the second element.

```
<?xml version="1.0"?>
   <p xmlns="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
      <r>
         <t>17 Shire Oak Road</t>
      </r>
      <r>
         <t>Saxlingham</t>
      </r>
      <r>
         <br/>
         <t>NR15 5TR</t>
      </r>
   </p>
```

Am I right in saying that their is a bug here in that the test for p.Elements().Count() on line 558 should test for > 0 not > 1 ??  And that the only reason why it works in the first case is because of the extra guff which is present artificially increasing p.Elements().Count()?  And that it should test only for a count of the <W:r> element?  Should it in fact show:

(p.Elements(W.r).Count() > 0)

This seems to work in my use case.

Cheers

Ben

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
