### ISSUE TITLE
While applying background color in the html theme is applied in the wml file

### ISSUE THREAD

**Issue by kaviyarasanaspire** [OfficeDev/Open-Xml-PowerTools#186]
While applying background color for the text if the image is inserted between the text with different font the theme is applied in the wml file and assigning different font.
 <w:rFonts w:asciiTheme="minorHAnsi" w:eastAsiaTheme="minorHAnsi" w:hAnsiTheme="minorHAnsi" w:cstheme="minorBidi" />

Can anyone please give me the solution for this.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
