### ISSUE TITLE
DOCX to PDF

### ISSUE THREAD

**Issue by vicpara** [OfficeDev/Open-Xml-PowerTools#187]
Hi,
I want to convert a DOCX file to PDF on any linux distribution you support. I just don't have a windows OS available. How can I do it. I've looked into the documentation and there is no trace of it.

Alternatively, is there a way to say which page contains a text fragment. For example, a text fragment has been identified on page number xx from the document yy,docx?

Thanks

**Comment by dam0vm3nt** [comment]
Hi. I'd like this feature too (exporting to PDF) but I think you will need an actual office installation for this. Infact this tools only deals with the file format and don't render anything. So there's no way you can render a docx file to pdf on linux using this library imho.

**Comment by ThomasBarnekow** [comment]
The feature you (and likely everybody else) would like to have would require a full rendering engine, which is not included in the Power Tools. You will have to use whatever other tools can print or publish a DOCX in PDF format.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
