### ISSUE TITLE
Document Assembler: Ability to merge in whole Word Documents or other Document Assembler templates

### ISSUE THREAD

**Issue by MalcolmJohnston** [OfficeDev/Open-Xml-PowerTools#191]
Hello, 

I wanted to check whether the above functionality would be useful to the project.  I have not contributed to  an Open Source project before so thought I would ask first before spending the time creating a Pull Request etc.

My implementation is as follows;

* Added two new elements; Document and DocumentTemplate
* These two elements share common attributes Path and Data
* The Path attribute can be either a file path or XPath that retrieves a file path from the input XML
* The Data attribute is intended to hold a base64 encoded string containing the Word document contents
* The DocumentTemplate element also has a Select attribute so that XML data can be passed to the template

e.g.

```
<Repeat Select="//Invoice" />
<DocumentTemplate Path="SubTemplate.docx" Select="." />
<Document Path="Terms.docx" />
<EndRepeat />
```

With the above in place what I do is take a two pass approach.

Firstly I process the Document and DocumentTemplate elements converting all to a Document element which contains a Data attribute with the base64 encoded content of the Document or assembled DocumentTemplate.

Then I have introduced a second step and as such a dependency on DocumentBuilder in DocumentAssembler.  I am not sure if this will be frowned upon or not :)

This second step is largely based on this post from Eric White;

https://blogs.msdn.microsoft.com/ericwhite/2009/04/21/using-documentbuilder-with-content-controls-for-document-assembly/

There are some limitations in my implementation, namely that all sections need to have the same page layout.  I will also (at some point) improve it slightly so that the the Document and DocumentTemplate elements will allow the addition of Page Breaks via an attribute.  This will make the template composition in word a lot neater.

Anyway, is anyone interested in this?  Or is my solution horrible!

I do think that this adds a LOT of power to DocumentAssembler and has the potential to make creating complex templates files more manageable by hiding away parts of templates into sub-templates.

If there is interest from the maintainers then I will put up a Pull Request.

Cheers.

**Comment by winterlaite** [comment]
I, for one, would be very, very interested in seeing your code. What you describe is a great idea.

**Comment by MalcolmJohnston** [comment]
Hi @winterlaite just to let you know that I have finally found some time to put the pull request together.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
