### ISSUE TITLE
MarkupSimplifier.SimplifyMarkup w:hint issue

### ISSUE THREAD

**Issue by bestplay** [OfficeDev/Open-Xml-PowerTools#192]
OpenXML power tools 4.5.3.2 from Nuget.

When I edit my docx in a RUN with <w:hint="east asia">.

It will add new RUNs with or without <w:hint>.

Then the SimplifyMarkup method can not merge this new RUNs.

Any help?

My tricky work round is Add the same <w:int> to each adjacent runs.

But i don't know if some bad things will happen.

I have read the document about hint:

> hint (Font Content Type) | Specifies the  font type which shall be used to format any ambiguous characters in the current  run.   There are  certain characters which are not explicitly stored in the document, and can be  mapped into multiple categories of the four mentioned above. This attribute  shall be used to arbitrate that conflict, and determine how ambiguities in this  run shall be handled. [Note: This is  primarily used to handle the formatting on the paragraph mark glyph, and other  characters that are not stored as text in the WordprocessingML document. end note]   If this  attribute is omitted, then this ambiguity can be resolved by any means  available.   [Example: Consider the run representing the  paragraph mark glyph, which is not stored as a physical character. Since this  could therefore be formatted with any of the fonts specified for the run, this  ambiguity is resolved using the following WordprocessingML:   <w:pPr><w:rPr><w:rFonts w:hint="eastAsia"  /></w:rPr></w:pPr>   The hint attribute specifies that the run must use the eastAsia font  (theme or not, whichever is in use for East Asian text) as defined for this  range. end example]   The possible  values for this attribute are defined by the ST_Hint  simple type (17.18.41).

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
