### ISSUE TITLE
imported word document not supporting for Listitems

### ISSUE THREAD

**Issue by saritakhachane** [OfficeDev/Open-Xml-PowerTools#193]
We have use OpenXML power tool 4.5.3.2 in our MVC project for importing word document.  after importing we are allowing user to edit it. But as list-items in Document are  imported with special CSS classes and not as UL LI ,so after hitting enter key  at the end of any bullet list item, next bullet list item wont created automatically. 
Please guide us on, how we can import word document with list-items, so that next list-item will automatically created after hitting enter key in Edit mode.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
