### ISSUE TITLE
Inline conditional not properly working

### ISSUE THREAD

**Issue by alejandronic** [OfficeDev/Open-Xml-PowerTools#195]
Hi, 
I need to make a sentence with the data i have in my XML, where some values should appear and some not. So I tried something like this:
XML:
<xml>
	<Condition1>true</Condition1>
    <Value1>5</Value1>
    <Condition2>true</Condition2>
    <Value2>5</Value2>
</xml>
DOCX:
<# <Conditional Select="./Condition1" Match="true"/> #>Value 1:<# <Content Select="./Value1"/> #><# <EndConditional/> #>,<# <Conditional Select="./Condition2" Match="true"/> #>Value 2:<# <Content Select="./Value2"/> #>.<# <EndConditional/> #>

When i open the returned file where it should be some values i get an id that is not anywhere in my xml.
Something like:
Value1 : a2d68399-ae3d-4374-a22c-737bc52ab9df, Value 2: a2d68399-ae3d-4374-a22c-737bc52ab9df
also condition1 was false so it shouldnt show anything.

If i wirte every line on different row it works great, but i get the resultant text in different rows.
Example:
<# <Conditional Select="./Condition1" Match="true"/> #>
Value 1:<# <Content Select="./Value1"/> #>
<# <EndConditional/> #>

How can i make this work as i want?
Sory for my bad english.
Thank you for the great work.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
