### ISSUE TITLE
Support for converting textboxes in .docx  to html

### ISSUE THREAD

**Issue by sandhyarkr** [OfficeDev/Open-Xml-PowerTools#196]
Hi,
I am using OpenXmlPowerTools 4.5.3.2 for my project to convert .docx files to html . I have found that the  textboxes within the .docx files are not being converted into html. Is this feature likely to be supported? 
I am doing this project as part of my organization requirement and most of the .docx files have textboxes and embedded data within the same which needs to be seen in the converted html .
I am using Visual Studio 2012 with Update 5 applied and have retrieved the OpenXMLPowertools library through NuGet. 

Also are any enhancements likely on making the html responsive?

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
