### ISSUE TITLE
Images Support

### ISSUE THREAD

**Issue by mesteves** [OfficeDev/Open-Xml-PowerTools#201]
Hi any plans to include something image support like this fork 

https://github.com/krembf/Open-Xml-PowerTools/commit/3779fc4f8ed11432b81f133a095f0fc3fe84c86e

Thanks in advance!

**Comment by MalcolmJohnston** [comment]
I have made a minor improvement to @boriskreminskimoldev fork (added an Optional attribute to remove images where no file or data is found) and would be happy to create and put up a pull request.

But I don't want to step on anyone's toes!

**Comment by krembf** [comment]
@MalcolmJohnston sure, feel free to create a pull request, glad to see this feature being improved!

**Comment by MalcolmJohnston** [comment]
@krembf thanks for putting the pull request together since I didn't get round to it.  Once it is merged in hopefully I will find the time to put my minor improvements in.

Thanks again for your work on this.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
