### ISSUE TITLE
DocumentAssembler generates large file

### ISSUE THREAD

**Issue by dkitchen** [OfficeDev/Open-Xml-PowerTools#202]
The size of the Assembled Document is around the same size as the template (word doc) from which it was produced. In my current case, this is a problem, because my word doc template is 27 megs, but has numerous conditionals (especially around large images I need to hide/show based on data). 

After the doc is assembled, I expect the assembled file to only be around 5 megs. Testing this assertion, I can open the 27 meg assembled document into MS Word, make a small change (add a space for example), save it, and now the saved file is only around 5 megs. This can make a huge difference in user experience, for example, when my users attempt to use my generated document as attachments in mail systems with attachment size limits.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
