### ISSUE TITLE
Open xml documents rasterizing 

### ISSUE THREAD

**Issue by mojtabakaviani** [OfficeDev/Open-Xml-PowerTools#21]
please work on capability can easy rasterizing docx, xlsx and pptx pages

**Comment by EricWhiteDev** [comment]
This is an excellent idea.  However, probably not to be scheduled for this year and probably not next.  Pagination of WordprocessingML is a big project.

I've noted your request, and will bring it to the attention of the folks who set priorities.

**Comment by MaitreDede** [comment]
Hi @EricWhiteDev  :)

I would like to know if you have plans for rasterizing. I have been searching for days, but only expensive commercial products so far...
