### ISSUE TITLE
Regression in OpenXmlRegex.Replace 

### ISSUE THREAD

**Issue by pedro-w** [OfficeDev/Open-Xml-PowerTools#214]
[me.docx](https://github.com/OfficeDev/Open-Xml-PowerTools/files/1781634/me.docx)
[you.docx](https://github.com/OfficeDev/Open-Xml-PowerTools/files/1781636/you.docx)

I've got a program using OpenXmlRegex.Replace to replace text 'templates' in a Word document with new values. I am getting problems with version 4.5.3.2 which weren't in 4.5.3.1. It looks like, once the document exceeds a certain size, it starts to replace characters off by one position. I've done some work to get the smallest example I can.
```` C#
using System.IO;
using System.Text.RegularExpressions;
using DocumentFormat.OpenXml.Packaging;
using OpenXmlPowerTools;

namespace ConsoleApp3
{
    class Program
    {
        static void Main(string[] args)
        {
            var src = Path.GetFullPath("..\\..\\me.docx");
            var dest = Path.GetFullPath("..\\you.docx");
            File.Copy(src, dest, true);
            var doc = WordprocessingDocument.Open(dest, true);
            foreach (var part in doc.ContentParts())
            {
                var xdoc = part.GetXDocument();
                var content = xdoc.Descendants(W.p);
                OpenXmlRegex.Replace(content, rex, "", null);
                part.PutXDocument();
            }
            doc.Save();
        }
        static readonly Regex rex = new Regex("rd");
    }
}

````
This program is supposed to replace all instances of 'rd' in file 'me.docx' with nothing and write the result into 'you.docx'

My input file looks like
````
word 1 word 2 word 3 word 4 word 5 word 6 word 7 word 8 word 9 word 10 word 11 word 12 
word 13 word 14 word 15 word 16 word 17 word 18 word 19 word 20 word 21 word 22 
word 23 word 24 
````
... down to ...
````
word 5991 word 5992 word 5993 word 5994 word 5995 word 5996 word 5997 word 5998 
word 5999 word 6000 
````
And the output file starts off OK
````
wo 1 wo 2 wo 3 wo 4 wo 5 wo 6 wo 7 wo 8 wo 9 wo 10 wo 11 wo 12 wo 13 wo 14 wo 15 wo 16 wo 
```` 
but later becomes
````
481 wo 482 wo 483 wo 484 wo 485 wo 486 wo 487 wo 488 wo 489 wo 490 wo 491 wd 492 wd 493 
wd 494 wd 495 wd 496 wd 497 wd 498 wd 499 wd 500 wd 501 wd 502 wd 503 wd 504 wd 505 wd 
````
and stays like that to the end.
I've tried different combinations of text, regex and replacement but there is no obvious way to calculate when it will go wrong.

However if I downgrade my NuGet packages to 4.5.3.1 it works OK. It seems to be independent of the version of `DocumentFormat.OpenXml` used, I can upgrade that to 2.8.1 (from 2.7.1/2.7.2) with no effect.

I am happy to do some more investigation but I found it difficult to work out which revision in git corresponds to which version in NuGet as there are no git tags.

I am using Visual Studio 2017, .NET 4.6.2

**Comment by pedro-w** [comment]
I've made the example program a lot smaller. The problem is in `OpenXmlRegex.Replace` itself and not in any of the document manipulation that happens around it. The cause seems to be an element `<w:lastRenderedPageBreak />` which Word inserts (hence the dependency on the document size.)
This program
```` c#
using System.Text.RegularExpressions;
using System.Xml.Linq;
using OpenXmlPowerTools;

namespace ConsoleApp3
{

    class Program
    {
        static void Main(string[] args)
        {
            var s = XDocument.Parse(rawxml);
            s.Save("me.xml");
            var content = s.Descendants(W.p);
            OpenXmlRegex.Replace(content, rex, "", null);
            s.Save("you.xml");
        }
        static readonly Regex rex = new Regex("rd");
        const string rawxml = @"
<w:document xmlns:w=""http://schemas.openxmlformats.org/wordprocessingml/2006/main"">
  <w:body>
    <w:p>
      <w:r>
        <w:t>word 1</w:t>
      </w:r>
      <w:r>
        <w:lastRenderedPageBreak />
        <w:t>word 2</w:t>
      </w:r>
    </w:p>
  </w:body>
</w:document>";
    }
}
````
produces output (the file 'you.xml') for 4.5.3.2
```` xml
<?xml version="1.0" encoding="utf-8"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    <w:p>
      <w:r>
        <w:t>wo 1</w:t>
      </w:r>
      <w:r>
        <w:lastRenderedPageBreak />
      </w:r>
      <w:r>
        <w:t>wd 2</w:t>
      </w:r>
    </w:p>
  </w:body>
</w:document>
````
and this for 4.5.3.1
```` xml
<?xml version="1.0" encoding="utf-8"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    <w:p>
      <w:r>
        <w:t>wo 1</w:t>
      </w:r>
      <w:r>
        <w:lastRenderedPageBreak />
      </w:r>
      <w:r>
        <w:t>wo 2</w:t>
      </w:r>
    </w:p>
  </w:body>
</w:document>
````
Hope that helps.

**Comment by pedro-w** [comment]
Previous work was with the NuGet packages. I've checked with the current vNext branch and I think maybe it has been fixed, specifically by commit fba2207ca00218257f4e3793958cface5e8dfa4b . Can you confirm if this sounds reasonable?

**Comment by ThomasBarnekow** [comment]
@pedro-w Yes, your problem sounds familiar and my commit fixed just that.

**Comment by pedro-w** [comment]
Thanks. Do you think the next version will be released imminently or is there much more work to do?

**Comment by ThomasBarnekow** [comment]
@pedro-w What do you mean with "will be released"? As a NuGet package?

**Comment by pedro-w** [comment]
Yes, exactly. It's more convenient to work with a dependency on NuGet. Thanks!

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
