### ISSUE TITLE
Add support for exporting images in .net core

### ISSUE THREAD

**Issue by arthurvb** [OfficeDev/Open-Xml-PowerTools#216]
Dear Reader,

Currently I cannot export images in .net core since ImageInfo has a bitmap property, where I get the following error:

Error	CS7069	Reference to type 'Bitmap' claims it is defined in 'System.Drawing', but it could not be found	DefaultProcessorImplementation	

when I want to use 'imageInfo.Bitmap.Save(ms, imageFormat);' in the ImageHandler. I did try to add the 'System.Drawing.Common' package from nuget, but that did not resolve the error.

Thank you in advance for your help and for making this package available,

Arthur

**Comment by ThomasBarnekow** [comment]
@arthurvb This does not sound like an issue with the Power Tools per se. You should consider posting a question on stackoverflow, for example.

**Comment by jacobbutton** [comment]
@arthurvb - I ran into the same issue a few months ago and wasn't able to resolve it.

Give this a shot - https://www.nuget.org/packages/System.Drawing.Common/4.5.0-rc1 - to make sure System.Drawing.Bitmap is referenced.

It didn't work for me, but there's been a few more iterations since I tried, with a new release candidate just a few hours ago. Maybe that fixes whatever was wrong? If you have any success I'd love to hear back. Good luck.

**Comment by jacobbutton** [comment]
For some clarification... this is where I'm getting the error.

`

	using (WordprocessingDocument wDoc = WordprocessingDocument.Open(memoryStream, true))
		[...]
		WmlToHtmlConverterSettings settings = new WmlToHtmlConverterSettings()
		{
			[...]
			ImageHandler = imageInfo =>
			{
				[...]
				imageInfo.Bitmap.Save([...]
				[...]
				ImageFormat format = imageInfo.Bitmap.RawFormat;
				[...]
			}
		}
		[...]
		XElement htmlElement = WmlToHtmlConverter.ConvertToHtml(wDoc, settings);
		[...]
	}

`

It's  OpenXML's WordProcessingDocument ImageHandler that's throwing the error when trying to access  it's Bitmap class.  I can invoke stand alone System.Drawing.Bitmap class just fine elsewhere in my code without throwing errors. This error seems solely related to OpenXML and [it's lack of support for .Net Core](https://github.com/OfficeDev/Open-Xml-PowerTools/issues/116).

**Comment by arthurvb** [comment]
@jacobbutton Reading the comments on the issue you referred I think this indeed the cause, thank you.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
