### ISSUE TITLE
Can we have a nuget package for this?

### ISSUE THREAD

**Issue by MichaelSagalovich** [OfficeDev/Open-Xml-PowerTools#22]
There is a nuget package for this, but it is not official, I believe: https://www.nuget.org/packages/OpenXmlPowerTools/. Moreover, it is version 4.0, while 4.1 has already been released.

So, can we have a proper nuget package?

Thanks!

**Comment by EricWhiteDev** [comment]
This is a great idea.  I'll assign it to myself, but don't have any information on when I can address this.  I'm on vacation right now, and when I get back, will have some high priority projects that need to be done before I can work on anything else.

**Comment by EricWhiteDev** [comment]
I'm looking for some help here - if anyone has bandwidth and experience to put together changes to the csproj / sln files so that it produces a Nuget package, would be helpful.  We can then create and keep updated a nuget package.

**Comment by MichaelSagalovich** [comment]
Unfortunately, I do not have such expertise, though it looks to be rather
trivial in theory.

**Comment by EricWhiteDev** [comment]
I pinged the fellow who created the unofficial Nuget package.  Maybe can team up with him to get this done.  Would be awesome!

**Comment by Hedath** [comment]
Any news on this?

**Comment by BrettBailey** [comment]
I've dabbled in this area (I have a nuget package on an internal server for my fork of powertools) and might be able to help out if the unofficial nuget guy isn't interested.

The way I would tackle this would be to use teamcity on code better http://codebetter.com/codebetter-ci/ to do CI on the master branch and auto publish to nuget.org evertime you merge vNext into master.

However to get this to work the referencing between powertools and sdk needs sorting out.  SDK Needs to be first made into a nuget package and powertools needs to to consume that nuget instead of having the direct dll reference.   

Then it will be easy and automatic.

**Comment by MichaelSagalovich** [comment]
Oh, SDK itself is not in nuget??? Come on! Is not it ridiculous?

**Comment by MichaelSagalovich** [comment]
ehm, sorry, for some reason I thought SDK was something developed by Microsoft :)

**Comment by Hedath** [comment]
The SDK already has a nuget package:
https://www.nuget.org/packages/documentformat.openxml/

**Comment by anantu** [comment]
It is outdated..

**Comment by gabisandor** [comment]
Is the plan to have an official, up-to-date NuGet package abandoned after all...?

**Comment by BrettBailey** [comment]
Maybe some of the folks who are clearly desperate for this can chip in and make it happen?  Google how to do it and make a pull request and collect some kudos.

**Comment by EricWhiteDev** [comment]
I think that the correct approach is that first, we need a NuGet package for the open source Open-Xml-Sdk, and then to create a NuGet package for Open-Xml-PowerTools that is dependent on the Open-Xml-Sdk.  I believe that the correct approach is to modify the build steps for the two libraries to create the NuGet package, and then it becomes easy to update the NuGet package whenever we have incorporated pull requests.

I would really welcome some help in this area.  I currently have too much high priority work to attend to this right now to attend to this.  I will get to it as soon as my schedule permits, but if a NuGet expert is able to do the bulk of the work, I can incorporate the changes as soon as they are available.

**Comment by gabisandor** [comment]
Well i could give it a shot, i used on a (non-GitHub) project NuGet Package Explorer (https://npe.codeplex.com/) in order to create and publish NuGet packages to an internal server. Maybe doing it in GitHub it's not very different; i'll try to see what i can do and if anything worthy comes out of it i'll launch a pull request.

**Comment by gabisandor** [comment]
I continued the discussion regarding Open XML SDK NuGet packages in its original thread: https://github.com/OfficeDev/Open-XML-SDK/issues/2.

**Comment by japj** [comment]
Hello, it seems there are OpenXML SDK (2.6.0) and PowerTools (4.2.0) Nuget packages published by Ranjith Venkatesh at https://www.nuget.org/profiles/ranjithvenkatesh

Do these happen to be the officially supported nuget packages?

**Comment by tomjebo** [comment]
Closing #22. 

We now have a nuget package available on the myget feed. See: 
[https://github.com/OfficeDev/Open-XML-SDK#ci-builds](url)
for instructions on how to access.

**Comment by gabisandor** [comment]
@tomjebo you are referring to an Open XML SDK NuGet package, not an Open XML PowerTools one. I don't think there is an official one available for the power tools yet. 

Gabriel

**Comment by tomjebo** [comment]
@gabisandor yes, I realized that after posting. that's why I deleted it. Sorry.

**Comment by kimsey0** [comment]
@tomjebo: Now that the Open XML SDK is available on MyGet, could the PowerTools be published there as well? Could we contribute to making that happen from outside Microsoft?

**Comment by tomjebo** [comment]
@kimsey0 We like the suggestion of approved contributors being able to push to NUGET. We need to do some research into what that entails. Thank you for bringing it up.

**Comment by kimsey0** [comment]
@tomjebo Just having an official package on NuGet would be wonderful, no matter how updates were pushed to it. I expect you have a CI system that builds and packages the SDK for https://dotnet.myget.org/gallery/open-xml-sdk. What I was thinking of was if we could do anything to prepare the PowerTools repository for going through the same process?

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
