### ISSUE TITLE
How from. XLSX converted into HTML?

### ISSUE THREAD

**Issue by hjdo** [OfficeDev/Open-Xml-PowerTools#220]
Hello, I encountered this problem, after searching the community and documentation still did not answer, so excuse me, if you can help me answer it?
thank you very much!

**Comment by ThomasBarnekow** [comment]
@haijiandong Can you be a little more specific as to what you are looking for?

Do you want to use the Open XML Power Tools to transform an Excel document to HTML? Did you already have a look at the source code to see whether you can find that functionality?

Not sure whether @EricWhiteDev has anything in the making, but I am not aware of that capability in the current version.

**Comment by haijiandong** [comment]
@ThomasBarnekow  Thank you for replying my question. I did not find the ability to convert excel to html in this project. may be what I missed.
Looking forward to having a good result. Thanks again.

**Comment by ThomasBarnekow** [comment]
Just to be sure, I don’t think you missed anything. The PowerTools do not offer that feature.

You could ask @ErivWhiteDev whether he is working on something in that direction.

**Comment by haijiandong** [comment]
Thank you @ThomasBarnekow .
Looking forward to the good news of @ErivWhiteDev . But I don't want to ask for the demand like a product manager, which can be very annoying. 😂😂😂

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
