### ISSUE TITLE
Add support for emf/wmf images conversion into html 

### ISSUE THREAD

**Issue by kokhany** [OfficeDev/Open-Xml-PowerTools#222]
It's known issue that GDI consumes huge amounts of memory when dealing with emf/wmf.

On the other hand, image/x-emf, image/x-wmf are valid types of images in both OpenXML and RTF specs.

While it still possible to replace these images with converted analogs using OpenXML SDK, it would be useful to allow convert a document with them into html (instead of just ignoring silently).
It's much simpler to convert them into another format in ImageHandler(png, for instance, because Chrome and Firefox don't understand emf/wmf formats), instead of replacing the ImagePart.

Moreover, the changes are really small, and, as the benefit, give the responsibility to the consumer what to do with these formats (they can be ignored as well).

Thanks in advance

**Comment by BradDuncan** [comment]
Agreed!  I ran into this issue today.  I can convert the x-emf, convert to a png, and create the embedded image string but no have mechanism to insert.  Furthermore, there is no commenting in the HTML (or warning) that the image was excluded.
The change does seem rather trivial.  If nothing else, allowing the user to perform the conversion on these files through the image callback.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
