### ISSUE TITLE
ChartUpdater: Support for Combo charts

### ISSUE THREAD

**Issue by VictorIranzo** [OfficeDev/Open-Xml-PowerTools#224]
Hi,
We are interested in ChartUpdater working with Combo charts. The combo charts are those that mix series of different chart types. A combo chart can be done using Word as shown at the screenshot:
 
![image](https://user-images.githubusercontent.com/27296704/40357379-4cb39ce6-5dbc-11e8-9440-dc050b7c3ce6.png)

We have tested the current ChartUpdater component for replacing the values of this chart in a DOCX:
 
![image](https://user-images.githubusercontent.com/27296704/40357386-53e63dfc-5dbc-11e8-9e1e-475d3d3267a1.png)

This chart combines two series: one is a bar chart and the other a line chart, with only the dots and in the secondary axis.

We provide in this repository an application that tests this: 
https://github.com/VictorIranzo/UpdateComboChart 

The result obtained is not the expected one. It seems that the ChartUpdater has added the new values of the two series in the bar chart section and has kept the section of the line chart. We couldn’t open the output document using Word, but if we use another editor like LibreOffice we see the mentioned result:
 
![image](https://user-images.githubusercontent.com/27296704/40357400-5ca8e692-5dbc-11e8-9a7b-4bdb94b3e685.png)

As you see, there are 3 series. The ‘Percentage’ series contains the data of the old chart. If we remove the line series manually opening the ‘chart1.xml’ file of the document, we realize that the values provided for the new chart have been inserted in the bar chart section:

![image](https://user-images.githubusercontent.com/27296704/40357421-6c11038a-5dbc-11e8-924d-ce533c87e458.png)
 
As we said, we are interested in this feature. We would like to know if you have planned to implement this feature.
Thanks 

**Comment by jjjmuniz** [comment]
@VictorIranzo I have written a solution that adds support for combo charts, as well as secondary axis for ChartUpdater. But... is this repository still active? @tomjebo @ThomasBarnekow @EricWhiteDev

**Comment by VictorIranzo** [comment]
Great news! It's nice to see someone replying to this issue after a long time. Where could I see the features that you mentioned? Have you planned to open a PR? 

Related to your question, Eric White announced some days ago a new release of this library in the #42 issue. However, it seems that the new commits will be more related with the DocumentAssembler than the ChartUpdater.

**Comment by jjjmuniz** [comment]
#245 mentions this module also. I think the more that people are wanting to use the edge cases of Charts, the more motivation there is to refactor the module.

Part of the difficulty is that certain assumptions are baked into the algorithm, and solving these edge cases tends to introduce new ones.

For example, it is assumed that all data series ~~are~~ belong to a single parent element and that they should be colored from the six accent colors from the document theme. This works fine for most use cases.

When I write an algorithm to enable the generation of combo Charts, I have to make new assumptions about what to do, for instance, when the ChartData had more series than the template does. Should the new series elements be inserted after the last c:ser? If so, do we mean last in document order or the one with the highest c:id?

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
