### ISSUE TITLE
This is no Open-Xml-PowerTools.psm1 file, that I can import module to PS

### ISSUE THREAD

**Issue by v-fanfan** [OfficeDev/Open-Xml-PowerTools#226]

**Comment by nlsdg** [comment]
Correct. You need to build it first.
Follow the instructions from https://www.youtube.com/watch?v=60w-yPDSQD0.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
