### ISSUE TITLE
Accepting Revisions on a document that contains AlternativeFormatImportPart will remove the part

### ISSUE THREAD

**Issue by VladDragnea** [OfficeDev/Open-Xml-PowerTools#227]
Hi. I have this issue with any kind of document that contains altChunk element. Calling: OpenXmlPowerTools.RevisionAccepter.AcceptRevisions(wordDocument) on that document will remove all altChunk elements within the body of the document. I assume this is not supposed to happen, or am I wrong?
This is a simple version of a file on which this issue is happening:
[Test.docx](https://github.com/OfficeDev/Open-Xml-PowerTools/files/2090414/Test.docx)
and a scheenshot with the dom before:
![test](https://user-images.githubusercontent.com/15382360/41238189-9d92a646-6d95-11e8-8f3b-7f93cc501897.png)
And this is the document after calling AcceptRevisions:
[Test-accepted.docx](https://github.com/OfficeDev/Open-Xml-PowerTools/files/2090427/Test-accepted.docx)
with a screenshot of the dom:
![test-accepted](https://user-images.githubusercontent.com/15382360/41238247-c9bd16d4-6d95-11e8-97e3-c9c3c6e77eca.png)

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
