### ISSUE TITLE
How convert to Html with inline style instead of accomulating them into head-style tag?

### ISSUE THREAD

**Issue by ryzhovalexandr** [OfficeDev/Open-Xml-PowerTools#229]
I want to insert converted doc in div part of html page. I don't want to use frames.
Is there option to convert doc to html with inline style? for example instead of

`<head><style>...</style><head><body><p class="..">..</p></body>`

get just

`<body><p style=".."><span style=".."></span></p></body>`

**Comment by EricWhiteDev** [comment]
Currently that isn't a feature of the Open-Xml-PowerTools.  It would not be too hard, but this isn't implemented.  But what you could do is to use the HtmlAgilityPack (or LINQ to XML in combination with HtmlAgilityPack to insert the right elements into your page at the proper place, and to merge the contents of the style element with the style element of the containing page...

**Comment by ryzhovalexandr** [comment]
@EricWhiteDev thank you

**Comment by ryzhovalexandr** [comment]
By the way, I've found nice solution with [PreMailer.Net](https://github.com/milkshakesoftware/PreMailer.Net)
