### ISSUE TITLE
Error: Sequence contains no elements when running DocumentBuilder on a server

### ISSUE THREAD

**Issue by DeuteriumCore** [OfficeDev/Open-Xml-PowerTools#234]
However, when I run part of the code that merges two documents on my computer, it works fine. Any help? Thanks!

Here is the code:
`using (WordprocessingDocument wDocIn = WordprocessingDocument.Open(mem, false))
                using (WordprocessingDocument wDocTemplate = WordprocessingDocument.Open(mem2, false))
                {
                    List<Source> sources = new List<Source>();

                    WmlDocument wmlIn = new WmlDocument("", mem);
                    WmlDocument wmlTemplate = new WmlDocument("", mem2);

                    sources.Add(new Source(wmlIn, true));
                    sources.Add(new Source(wmlTemplate, true));
                    
                    wmlIn = DocumentBuilder.BuildDocument(sources);

                    Output = wmlIn.DocumentByteArray;
                }`

Unfortunately, I cannot debug the program uploaded on the server since it's . . . OutSystems.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
