### ISSUE TITLE
While trying to convert the following word document to HTML the output has extra spaces between words.

### ISSUE THREAD

**Issue by pratisharora** [OfficeDev/Open-Xml-PowerTools#235]
While trying to convert the following word document to HTML the output has extra spaces between words.

See the input documnet the second word presentation is split to     prese  n  tation, the same goes for many other words.

Orignal document
[Pratish_DOC_SAmple.docx](https://github.com/OfficeDev/Open-Xml-PowerTools/files/2194734/Pratish_DOC_SAmple.docx)
Output
![image](https://user-images.githubusercontent.com/41182805/42721979-6cac83cc-8761-11e8-9829-885ab5ff6ae8.png)

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
