### ISSUE TITLE
Histogram chart support

### ISSUE THREAD

**Issue by tdolot** [OfficeDev/Open-Xml-PowerTools#239]
Hi,

Does OpenXmlPowerTools support Histogram chart? I've checked the code and it looks like Histogram is of type chartEx, I cannot find any reference to it anywhere. If it's not supported, are there any plans to add the support? Are there any technical reasons for which chartEx is not implemented?

Regards

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
