### ISSUE TITLE
Document with justified and left aligned text is incorrectly formatted when converting to html

### ISSUE THREAD

**Issue by Suresh-Subedi** [OfficeDev/Open-Xml-PowerTools#243]
Minimum markup for which conversation fails:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" 
    xmlns:cx="http://schemas.microsoft.com/office/drawing/2014/chartex" 
    xmlns:cx1="http://schemas.microsoft.com/office/drawing/2015/9/8/chartex" 
    xmlns:cx2="http://schemas.microsoft.com/office/drawing/2015/10/21/chartex" 
    xmlns:cx3="http://schemas.microsoft.com/office/drawing/2016/5/9/chartex" 
    xmlns:cx4="http://schemas.microsoft.com/office/drawing/2016/5/10/chartex" 
    xmlns:cx5="http://schemas.microsoft.com/office/drawing/2016/5/11/chartex" 
    xmlns:cx6="http://schemas.microsoft.com/office/drawing/2016/5/12/chartex" 
    xmlns:cx7="http://schemas.microsoft.com/office/drawing/2016/5/13/chartex" 
    xmlns:cx8="http://schemas.microsoft.com/office/drawing/2016/5/14/chartex" 
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
    xmlns:aink="http://schemas.microsoft.com/office/drawing/2016/ink" 
    xmlns:am3d="http://schemas.microsoft.com/office/drawing/2017/model3d" 
    xmlns:o="urn:schemas-microsoft-com:office:office" 
    xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" 
    xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" 
    xmlns:v="urn:schemas-microsoft-com:vml" 
    xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" 
    xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" 
    xmlns:w10="urn:schemas-microsoft-com:office:word" 
    xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" 
    xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" 
    xmlns:w15="http://schemas.microsoft.com/office/word/2012/wordml" 
    xmlns:w16cid="http://schemas.microsoft.com/office/word/2016/wordml/cid" 
    xmlns:w16se="http://schemas.microsoft.com/office/word/2015/wordml/symex" 
    xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" 
    xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" 
    xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml" 
    xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape" mc:Ignorable="w14 w15 w16se w16cid wp14">
    <w:body>
        <w:p w14:paraId="4F76327E" w14:textId="07E7AA7B" w:rsidR="007145F2" w:rsidRDefault="0013176D" w:rsidP="0073348A">
            <w:pPr>
                <w:ind w:left="-570"/>
                <w:jc w:val="both"/>
                <w:rPr>
                    <w:rFonts w:ascii="Arial" w:hAnsi="Arial"/>
                    <w:color w:val="222222"/>
                    <w:shd w:val="clear" w:color="auto" w:fill="FFFFFF"/>
                    <w:lang w:val="nl-BE" w:eastAsia="nl-BE" w:bidi="nl-BE"/>
                </w:rPr>
            </w:pPr>
            <w:r>
                <w:rPr>
                    <w:lang w:val="fr-FR" w:eastAsia="fr-FR" w:bidi="fr-FR"/>
                </w:rPr>
                <w:t>Police</w:t>
            </w:r>
            <w:r>
                <w:rPr>
                    <w:rFonts w:ascii="Arial" w:hAnsi="Arial"/>
                    <w:color w:val="222222"/>
                    <w:shd w:val="clear" w:color="auto" w:fill="FFFFFF"/>
                    <w:lang w:val="nl-BE" w:eastAsia="nl-BE" w:bidi="nl-BE"/>
                </w:rPr>
                <w:t xml:space="preserve"></w:t>
            </w:r>
        </w:p>
        <w:p w14:paraId="60D946B7" w14:textId="1C4DE7A7" w:rsidR="0073348A" w:rsidRPr="0073348A" w:rsidRDefault="0073348A" w:rsidP="005119DD">
            <w:pPr>
                <w:ind w:hanging="570"/>
                <w:rPr>
                    <w:lang w:val="fr-FR"/>
                </w:rPr>
            </w:pPr>
            <w:proofErr w:type="spellStart"/>
            <w:proofErr w:type="gramStart"/>
            <w:r>
                <w:rPr>
                    <w:rFonts w:ascii="Arial" w:hAnsi="Arial"/>
                    <w:color w:val="222222"/>
                    <w:shd w:val="clear" w:color="auto" w:fill="FFFFFF"/>
                    <w:lang w:val="nl-BE" w:eastAsia="nl-BE" w:bidi="nl-BE"/>
                </w:rPr>
                <w:t>ggg</w:t>
            </w:r>
            <w:bookmarkStart w:id="0" w:name="_GoBack"/>
            <w:bookmarkEnd w:id="0"/>
            <w:proofErr w:type="spellEnd"/>
            <w:proofErr w:type="gramEnd"/>
        </w:p>
        <w:sectPr w:rsidR="0073348A" w:rsidRPr="0073348A">
            <w:pgSz w:w="12240" w:h="15840"/>
            <w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" w:header="708" w:footer="708" w:gutter="0"/>
            <w:cols w:space="708"/>
            <w:docGrid w:linePitch="360"/>
        </w:sectPr>
    </w:body>
</w:document>

**Comment by Suresh-Subedi** [comment]
colon office colon is converted to icon by github

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
