### ISSUE TITLE
Tests fail because of OxPt.PbTests.PB006_VideoFormats on .Net Core

### ISSUE THREAD

**Issue by PhenX** [OfficeDev/Open-Xml-PowerTools#244]
Error : 
> [xUnit.net 00:00:04.23] OxPt.PbTests.PB006_VideoFormats [FAIL]
> System.IO.IOException : Entries cannot be opened multiple times in Update mode.

Discussion here : https://github.com/OfficeDev/Open-Xml-PowerTools/pull/238#issuecomment-411069902

This is a bug in .net Core 2.0 runtime : https://github.com/dotnet/corefx/issues/26952

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
