### ISSUE TITLE
Page breaks not converted from Docx to HTML

### ISSUE THREAD

**Issue by NicoJuicy** [OfficeDev/Open-Xml-PowerTools#248]
Page breaks are currently not supported in Docx to Html

I added a Pull Request ( https://github.com/OfficeDev/Open-Xml-PowerTools/pull/246 ) to fix this.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
