### ISSUE TITLE
ConvertToHtml have an issue with Strict Open XML Files

### ISSUE THREAD

**Issue by IrakliLomidze** [OfficeDev/Open-Xml-PowerTools#251]
ConvertToHtml have issue with Strict Open XML Files

...
   XElement htmlElement = WmlToHtmlConverter.ConvertToHtml(wDoc, settings);
Generate Null reference exception, But if document is in TRANSITIONAL DOCX format all works fine.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
