### ISSUE TITLE
Converting ordered/unordered lists

### ISSUE THREAD

**Issue by DiplIngAndreasScholz** [OfficeDev/Open-Xml-PowerTools#254]
When converting an ordered list to word using ConvertHtmlToWml output is always an unordered list.
Input: 
<html xml:space="preserve" xmlns="http://www.w3.org/1999/xhtml">   <ol>     <li>   ordered list</li>     <li>zwei</li>   </ol>   <ul>     <li>unordered list</li>     <li>bullet</li>   </ul> </html>

Output:
•	ordered list
•	zwei
•	unordered list
•	bullet

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
