### ISSUE TITLE
Bullets are broken when converting to html on the webview

### ISSUE THREAD

**Issue by ShinShil** [OfficeDev/Open-Xml-PowerTools#258]
**Error description**
I have converted docx to html with `HtmlConverter`. OpenXmlPowerTools version: 4.5.3.2

This is output for bullets list
```
 <p
        dir="ltr"
        class="pt-000005">
        <span
          class="pt-000006"></span>
        <span
          class="pt-DefaultParagraphFont-000003">Constipation</span>
      </p>
      <p
        dir="ltr"
        class="pt-000005">
        <span
          class="pt-000006"></span>
        <span
          class="pt-DefaultParagraphFont-000003">Itching</span>
      </p>
```
The square in `.pt-000006` is a bullet sybmol. It displays on the PC, but on the IOS you it looks in next way:
![image](https://user-images.githubusercontent.com/11064696/47010806-c05d7180-d148-11e8-80b1-7547ee0a4ea3.png)

Also the same problem for a lot of other characters, f.e. 
![image](https://user-images.githubusercontent.com/11064696/47011013-6a3cfe00-d149-11e8-800f-247289625fd2.png) 
these quotes will not display both on android and ios

**What expected**
Replace where possible characters with html codes, f.e. bullet code: `&bull;`

**Comment by ShinShil** [comment]
BTW I have found what the problem, resulting html uses some font-families, that are missing on the android. F.e. for bullets: `font-family: symbol`.

My current fix: 
```
               htmlContent = HtmlConverter.ConvertToHtml(doc, settings).ToStringNewLineOnAttributes();
               StringBuilder stringBuilder = new StringBuilder(htmlContent);
                var index = stringBuilder.ToString().IndexOf((char)61623);
                while (index != -1)
                {
                    stringBuilder.Remove(index, 1);
                    stringBuilder.Insert(index, "&bull;");
                    index = stringBuilder.ToString().IndexOf((char)61623);
                }

                File.WriteAllText(htmlFileName, stringBuilder.ToString());
```

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
