### ISSUE TITLE
when i convert a docx to html ,the format is wrong

### ISSUE THREAD

**Issue by liugt34** [OfficeDev/Open-Xml-PowerTools#259]
### **this is the docx**
![image](https://user-images.githubusercontent.com/8056013/47491442-6c0b6d80-d87d-11e8-81df-fa9f8da35a5d.png)

### **this is the html converted**
![image](https://user-images.githubusercontent.com/8056013/47491484-7f1e3d80-d87d-11e8-8a81-539d3f51dd41.png)

i find the css width  is to samll ,only 0.5in
![image](https://user-images.githubusercontent.com/8056013/47491710-fce24900-d87d-11e8-94ff-1fa09a86bfe2.png)

### **this is the docx file**
[010111.docx](https://github.com/OfficeDev/Open-Xml-PowerTools/files/2514264/010111.docx)

so how can i do the right work!

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
