### ISSUE TITLE
ConvertToHtml - docx convert to html without ContentControls

### ISSUE THREAD

**Issue by RachelBook3215** [OfficeDev/Open-Xml-PowerTools#260]
I try to convert docx to html using OpenXmlPowerTools. The .docx file has ContentControls, but the problem is that the content controls moves only with the text, instead of placeholder at the HTML file. 
I try to use 'SimplifyMarkupSettings' with the parameter 'RemoveContentControls' set to false, but it is doesn't work.
See at the code below.
`SimplifyMarkupSettings tabSettings = new SimplifyMarkupSettings
                    {
                        RemoveComments = false,
                        RemoveContentControls = false,
                        RemoveMarkupForDocumentComparison = false,
                        RemoveEndAndFootNotes = false,
                        RemoveFieldCodes = false,
                        RemoveLastRenderedPageBreak = false,
                        RemovePermissions = false,
                        RemoveProof = false,
                        RemoveRsidInfo = false,
                        RemoveSmartTags = false,
                        RemoveSoftHyphens = false,
                        ReplaceTabsWithSpaces = true,
                    };`

`

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
