### ISSUE TITLE
Multi-word fonts fail

### ISSUE THREAD

**Issue by jbarbara** [OfficeDev/Open-Xml-PowerTools#264]
Fonts like "Free 3 of 9" fail because they are not quoted in the resulted css/html

**Comment by jbarbara** [comment]
diff --git a/OpenXmlPowerTools/SmlToHtmlConverter.cs b/OpenXmlPowerTools/SmlToHtmlConverter.cs
index b83682a..a052ba6 100644
--- a/OpenXmlPowerTools/SmlToHtmlConverter.cs
+++ b/OpenXmlPowerTools/SmlToHtmlConverter.cs
@@ -301,7 +301,7 @@ namespace OpenXmlPowerTools
                 style.AddIfMissing("font-family", string.Format(FontFallback[font], font));
                 return;
             }
-            style.AddIfMissing("font-family", font);
+            style.AddIfMissing("font-family", $"'{font}'");
         }

         private static bool GetBoolProp(XElement runProps, XName xName)

jbarbara@jbarbara-l01 MINGW64 /d/Development/Open-Xml-PowerTools.master (vNext)
$ git commit -m "add quote around font always, multiword fonts fail without this" OpenXmlPowerTools/SmlToHtmlConverter.cs


the above should fix it making sure we always have quote around font-family values

I don't have access to the repo so maybe some else can add the one line in for me ?

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
