### ISSUE TITLE
Why remove bookmark and comment after compare

### ISSUE THREAD

**Issue by michaellomonosov** [OfficeDev/Open-Xml-PowerTools#268]
When I used this code
```
var doc11 = new WmlDocument("...\\1.docx");
var doc21 = new WmlDocument("..\\2.docx");
var result = WmlComparer.Compare(doc11, doc21, new WmlComparerSettings());
result.SaveAs("...\\out.docx");
```

Result doc didn't have comments or bookmarks, but there was. It's bug or feature?

**Comment by EricWhiteDev** [comment]
@michaellomonosov, retaining comments / bookmarks is not a feature of WmlComparer.  The organization that hired me to write that module (was not Microsoft) wanted only the functionality that is currently in WmlComparer.
