### ISSUE TITLE
DocumentAssembler and Page Number

### ISSUE THREAD

**Issue by GuyMetz** [OfficeDev/Open-Xml-PowerTools#27]
I was trying to Process a Document with DocumentAssembler that had a page number configured into the Footer. DocumentAssembler is trying to process the content of the Content Control that Word inserted as XML and replacing it with the Invalid Xml Message. This might be a more general problem in that DocumentAssembler appears to want to process all Content Controls in the Document?

**Comment by EricWhiteDev** [comment]
Yes, you are right.  DocumentAssembler should ignore content controls that are not specifically part of configuring the template.  I'll take care of this.

**Comment by EricWhiteDev** [comment]
I've pushed a change that fixes this.

https://github.com/OfficeDev/Open-Xml-PowerTools/commit/cdd270f21b36ca5e9052b3b8b3d3fe6139ba9b0e

**Comment by GuyMetz** [comment]
Thanks.

On Mon, Nov 2, 2015 at 5:09 AM, Eric White <notifications@github.com> wrote:

> I've pushed a change that fixes this.
>
> cdd270f
> <https://github.com/OfficeDev/Open-Xml-PowerTools/commit/cdd270f21b36ca5e9052b3b8b3d3fe6139ba9b0e>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OfficeDev/Open-Xml-PowerTools/issues/27#issuecomment-152976660>
> .
>



-- 
*Guy Metz*
