### ISSUE TITLE
DocumentAssembler: Error-Message of Repeat-Element might produce invalid DOCX

### ISSUE THREAD

**Issue by chrlutz** [OfficeDev/Open-Xml-PowerTools#29]
In the following case a Repeat-Element produces invalid DOCX:

If there‘s a Repeat-Element in a paragraph, mixed with other elements in the same paragraph AND the XPath-Evaluation for Repeat returns no result-nodes.

In this case Repeat produces an Error-Message like &lt;w:p>&lt;w:r>...Error-message...&lt;/w:r>&lt;/w:p> WITHIN the context of a &lt;w:p> element and I would get the following invalid result:

&lt;w:p>&lt;w:p>&lt;w:r>...Error-message...&lt;/w:r>&lt;/w:p>&lt;/w:p>

The usecase is: a template with "In-Paragraph Repitition" like this one:

![repeatissue29](https://cloud.githubusercontent.com/assets/10079489/10939484/37c2bcb4-8302-11e5-89cc-228d57c0fa51.png)

In most cases this is not a problem, because in most cases the Repeat-Element IS the current paragraph (small &lt;&lt; and >> symbols in the blue markers of the content controls). So the Repeat-Element (and the corresponding <w:p>) is just replaced by &lt;w:p>&lt;w:r>...Error-message...&lt;/w:r>&lt;/w:p> and everything is fine.

I guess this is because of https://github.com/OfficeDev/Open-Xml-PowerTools/blob/vNext/OpenXmlPowerTools/DocumentAssembler.cs#L608
not being aware the current context.

**Comment by EricWhiteDev** [comment]
The new logic that takes context into account when creating an error fixes this situation.  I have added a test for this.

**Comment by EricWhiteDev** [comment]
@chrlutz, @BrettBailey Christoph, Brett, if both of you would kindly pull the latest, check it out, I would appreciate it.
