### ISSUE TITLE
DocumentAssembler: typo in Repeat element leeds to invalid docx result

### ISSUE THREAD

**Issue by chrlutz** [OfficeDev/Open-Xml-PowerTools#31]
I had the following situation:

![repeatissue31](https://cloud.githubusercontent.com/assets/10079489/10939231/7329f99a-8300-11e5-9106-3e141f0b62ad.png)

Please note the typo in the Repeat statement: "Secelt" should be "Select".

This typo leads to an invalid docx result. So for a template creator this means the corresponding error message cannot be viewed because the result document (that contains the error message) could not be opened in word. Another big pitfall! I had to inspect the document on xml level before I found the reason.

I would expect DocumentAssembler to not produce invalid documents in any case. 

This issue again could be related to #29 , but I'm not sure here. In contrast to #29 the Repeat and EndRepeat elements are not "in paragraph" (the small &lt;&lt; and >> symbols in the blue markers are visible)

**Comment by EricWhiteDev** [comment]
I agree, DocumentAssembler should never generate an invalid document!

The case was an orphan EndRepeat metadata element that was left in the document.  I modified DocumentAssembler to look for these and replace with an error paragraph.  I added tests, and they now properly process a Repeat with a schema error.
