### ISSUE TITLE
HtmlToWmlCssApplier double conversion

### ISSUE THREAD

**Issue by Hedath** [OfficeDev/Open-Xml-PowerTools#38]
Hi!
The ComputeAbsoluteLength method in the HtmlToWmlCssApplier class converts string values to double with this code (line 1424):
```C#
!double.TryParse(value, out decValue) 
```
Unfortunately, this uses CultureInfo.CurrentCulture, but the ComputeAbsoluteLength method assumes that the double value should contain a dot, not a comma.
If you run this code on a machine with a CultureInfo that expects a comma in the double value, this code will fail.
Example:
If I run this on a machine with hu_HU culture info, this code can't convert "2.38" to 2.38, because it expects a comma, which is obviously wrong.

Changing the TryParse calls to this should solve the problem:
```C#
!double.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out decValue)
```

**Comment by EricWhiteDev** [comment]
You are absolutely right.  I'm in the middle of some other code, but should get to a good stopping point, and will make that change right away.

**Comment by EricWhiteDev** [comment]
@Hedath I've made and pushed the change.  Thanks for the help!
