### ISSUE TITLE
DocumentAssember:  Unit tests for generated documents that won't open.

### ISSUE THREAD

**Issue by BrettBailey** [OfficeDev/Open-Xml-PowerTools#40]
I've hit a number of issues where a document has been assembled correctly, no errors raised but the document just won't open.

Its usually because of missing xml tags that can be rectified by putting spaces in the template. There is big risk that an end user may tweak the template wording and accidentally remove some white space that causes us to email documents to customers that won't open.

I would like to write small unit tests to isolate the issue. (and then fix properly)

Not sure how to do it though :-(  Is there a schema anywhere we could validate the output against?

**Comment by EricWhiteDev** [comment]
@BrettBailey Sorry, I don't understand "missing xml tags that can be rectified by putting spaces in the template".  Are you speaking of the metadata XML?  Each of the metadata XML is validated per schemas that are embedded in DocumentAssembler.cs.  Removing spaces should cause the XML to be invalid, putting up the appropriate error.

To start, can you submit a PR for some test cases that fail?

One idea - with regards to naming / numbering of test documents, if you start with, say, 400, and other developers use a different range, then merging is a tiny bit easier.  :-)  So your test documents would be DA401-MissingSpacesFirstCase.docx, or some such.

**Comment by BrettBailey** [comment]
"missing xml tags that can be rectified by putting spaces in the template"

My suspicion is that, sometimes,  if a conditional  is the only content in a paragraph or table then and the contrition is not satisfied the replacement code can mess up and leave you with a word document that will not open.  I've not isolated the specific problem but adding extra whitespace around the conditional tag in the template docx has so far solved the problem.

Document assembler does not detect the problem so the standard unit test will pass even when there is an issue.

The next time this crops up I will try and isolate the issue into a small file and put it in a PR.

**Comment by EricWhiteDev** [comment]
I significantly changed that code yesterday and today.  I believe your issue will be resolved, I hope, anyway.  Closing for now.  Can reopen it as necessary.
