### ISSUE TITLE
HTML Converter: Images position

### ISSUE THREAD

**Issue by Tokebluff** [OfficeDev/Open-Xml-PowerTools#43]
The docx to Html Converter takes the image and adds a img element inside a span element on the html generated, but all the spans have `white-space: pre-wrap` (because of this setting : `GeneralCss = "span { white-space: pre-wrap; }";` ) and because of that all the images are shifted to the right  when the image is on the left side of the document, and shifted down when the image is on the right side of the document. If the `white-space: pre-wrap` CSS is removed from all the spans then the html has no spaces between all elements.

I fixed that by adding a new css class which overwrites the `white-space: pre-wrap` with `white-space: nowrap` for the spans that have an img element inside with jquery after the html has been generated.

**Comment by EricWhiteDev** [comment]
Do you think that the default css as shipped should have white-space: nowrap?

**Comment by Tokebluff** [comment]
Only the spans that have an img tag inside. I fixed it by replacing the General Css with `span { white-space: pre-wrap; } .nowrapwhitespace {white-space:nowrap !important;}` and then with jquery `$('img').parent().addClass ("nowrapwhitespace");` so I can add that css class to the spans containing an image.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
