### ISSUE TITLE
DocumentAssembler - Having an Else construct for Conditional

### ISSUE THREAD

**Issue by EricWhiteDev** [OfficeDev/Open-Xml-PowerTools#44]
With the newly added NotMatch, possible to have two alternative pieces of content based on a match.  It would be cleaner, markup wise, to have an Else.

We have both block-level, and run-level conditional, and Else would be applicable in both these scenarios.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
