### ISSUE TITLE
Some tests fail when Regional Format is Dutch (Netherlands)

### ISSUE THREAD

**Issue by JanVanderschoot** [OfficeDev/Open-Xml-PowerTools#46]
Two tests (named T0010.html and T0013.html) fail when the Regional Settings in Control Panel are Dutch (Netherlands). All tests succeed when this is setting is changed to English (US).

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
