### ISSUE TITLE
HtmlToWml - font tag support

### ISSUE THREAD

**Issue by k59319** [OfficeDev/Open-Xml-PowerTools#49]
I have a HTML fragment from SharePoint rich text field and I need to paste it into a Word document. The converter works good but it ignores 'font' tag at all.

``` html
<div class="ExternalClassEE9830F7214044AA993ADA217D2B5BBE"><font color="#ff91d2"><b>paragraph 1</b></font></div>
```

It has black font color in .docx after conversion.
The full html fragment is attached.
[html.txt](https://github.com/OfficeDev/Open-Xml-PowerTools/files/59445/html.txt)

**Comment by EricWhiteDev** [comment]
@k59319 You are right, HtmlToWml should support the font tag.

I anticipate jumping back into Open-Xml-PowerTools development in a couple of months, after I complete the port of the Open-Xml-Sdk to Office 2016, which will be v3.0 of the SDK.  I'll address this issue then.

**Comment by NavaneethaDev** [comment]
@k59319  did you try using "userCss" parameter in HtmlToWmlConverterCore.ConvertHtmlToWml method?

You could pass your styles as string. Refer the below example.

.ExternalClassEE9830F7214044AA993ADA217D2B5BBE
{
color:#ff91d2;
}

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
