### ISSUE TITLE
Stream writing XLXS 

### ISSUE THREAD

**Issue by dotnetdan** [OfficeDev/Open-Xml-PowerTools#54]
Hi, the readme page mentions the following capability:

     Writing XLSX files using far simpler code than directly writing the markup, including a streaming approach that enables writing XLSX files with millions of rows.

I can't seem to find an example of this.  Can anyone provide any guidance on how to to this?  What I'm hoping to do is generate a large XLSX file in a WEBAPI service and stream the output without buffering the file in memory.

**Comment by EricWhiteDev** [comment]
Hi,

Take a look at the following screen-cast:

http://openxmldeveloper.org/blog/b/openxmldeveloper/archive/2012/01/10/screen-cast-using-open-xml-and-linq-to-xml-in-a-streaming-fashion-to-create-huge-spreadsheets.aspx

A further modified and cleaned up version of this class is included in Open-Xml-PowerTools.

There needs to be an example of the use of this class in Open-Xml-PowerTools.  I've added it to my todo list.  :-)

Cheers, Eric
