### ISSUE TITLE
HTMLConverter: Self-closed hyperlink tag issue

### ISSUE THREAD

**Issue by anetegithub** [OfficeDev/Open-Xml-PowerTools#56]
Big issue with self-closing tags in docx when converting to html.
See attached files:
![notprocessed](https://cloud.githubusercontent.com/assets/6468447/12409509/83913dc6-be8c-11e5-8939-5ce41d281ced.PNG)

![processed](https://cloud.githubusercontent.com/assets/6468447/12409488/563c18b4-be8c-11e5-83b2-4c326d89e97d.PNG)
![bug1](https://cloud.githubusercontent.com/assets/6468447/12409470/2b05b6b4-be8c-11e5-9771-286e3614b811.PNG)

Example:
[Bug.docx](https://github.com/OfficeDev/Open-Xml-PowerTools/files/95314/Bug.docx)

**Comment by EricWhiteDev** [comment]
@anetegithub Can you please tell me more about what the issue is?  If the resulting HTML is not what you expect, what do you expect?

Cheers, Eric

**Comment by anetegithub** [comment]
If i used Word->File->Save as..->Html:

```html
<div class="WordSection1">
    <p class="ConsPlusNormal" style="text-align:justify;text-indent:27.0pt">
        <span lang="EN-US" style="mso-ansi-language:EN-US">Text</span>
        <a href="application://offline/ref=058CBF09D0EE2CD56FD997C0621A2DD3587C21AF7AD20022D25EC614C8434C37592398MFy0G"></a>.
    </p>
    <p class="ConsPlusNormal" style="text-align:justify;text-indent:27.0pt">
        <span lang="EN-US" style="background:yellow;mso-highlight:yellow;mso-ansi-language:EN-US">Will be hyperlink).</span>
        <span lang="EN-US" style="mso-ansi-language:EN-US"><o:p></o:p></span>
    </p>
    <p class="ConsPlusNormal" style="text-align:justify;text-indent:27.0pt">
        <span lang="EN-US" style="mso-ansi-language:EN-US">Will be hyperlink too<o:p></o:p></span>
    </p>
</div>
```

HtmlConverter:
```html
<div>
    <p dir="ltr"
       class="pt-ConsPlusNormal">
        <span class="pt-a0">Text</span>
        <a href="application://offline/ref=058CBF09D0EE2CD56FD997C0621A2DD3587C21AF7AD20022D25EC614C8434C37592398MFy0G" />
        <span lang="ru-RU" class="pt-a0">.</span>
    </p>
    <p dir="ltr" class="pt-ConsPlusNormal">
        <span class="pt-a0-000000">Will be hyperlink).</span>
    </p>
    <p dir="ltr" class="pt-ConsPlusNormal">
        <span class="pt-a0">Will be hyperlink too</span>
    </p>
</div>
```
Difference:
```html
></a>
```
```html
/>
```

In outlook '07-'13 rendered:

![563c18b4-be8c-11e5-83b2-4c326d89e97d](https://cloud.githubusercontent.com/assets/6468447/12542107/d54d8030-c340-11e5-98f3-f3a9dbd0ccd0.PNG)

**Comment by EricWhiteDev** [comment]
@anetegithub I just pushed a commit into the vNext branch that forces hyperlink (a) elements to be empty elements instead of self-closing.  Please give it a try, let me know.

I didn't address elements other than the 'a' tag.  If you have specific elements that also need this treatment, please let me know.

FWIW, this is a bug in Outlook - a self-closing tag is defined to be the same as an empty element, per the XML spec.  In any case, it's ok to make them empty elements, and if it makes Outlook behave properly, then that is good.

**Comment by anetegithub** [comment]
@EricWhiteDev  So, at this point i understood that it is exceptional bug in outlook since 2007...
In my current project i will set empty space in empty tags to avoid this problem.
I think this thread can be closed.
