### ISSUE TITLE
Is CommentMerger functionality still available?

### ISSUE THREAD

**Issue by dbeaulieu** [OfficeDev/Open-Xml-PowerTools#6]
[CommentMerger](http://blogs.msdn.com/b/ericwhite/archive/2009/08/11/update-to-commentmerger-mergecomments-method.aspx) was part of OOXML PowerTools (It is in [v2.2 on CodePlex](https://powertools.codeplex.com/downloads/get/291022))

Was this removed and if so, is there an alternate/recommended way of achieving comment merging?

**Comment by EricWhiteDev** [comment]
CommentMerger was removed - there were issues associated with the case where the documents were not identical, except for comments, and if I remember correctly, CommentMerger could produce an invalid document, so I removed it until I could properly address the issue.
