### ISSUE TITLE
WmlToHtmlConverter text boxes 

### ISSUE THREAD

**Issue by aMcafee** [OfficeDev/Open-Xml-PowerTools#61]
I noticed in [this post](http://openxmldeveloper.org/blog/b/openxmldeveloper/archive/2014/01/30/transform-docx-to-html-css-with-high-fidelity-using-powertools-for-open-xml.aspx), back in 2014, that there were plans to support converting MS Word text boxes to HTML. At the moment text boxes seem to be more or less ignored. So I was wondering if there has been any update since that post on if/when text boxes will be supported? Or if there is a work around anyone knows about to be able to convert text boxes? 

Thank you for any info you can give me and for the great tool!

**Comment by EricWhiteDev** [comment]
This is something we contemplated doing at the same time as support for floating images, as text boxes share a lot in common with floating images.  I will be doing a round of enhancements in Feb or Mar on Open-Xml-PowerTools.  I am not yet certain about what we will be doing in that round, but will make sure that this is on the list of enhancements to be considered.  Leaving this issue open for the time being.

**Comment by aMcafee** [comment]
That's great to hear! Thank you!

**Comment by bguyb** [comment]
Hi
I'm trying to convert and text boxes are not showing at all in the result HTML.
Version 4.5.3.2
Is it supported?
Tx

**Comment by johnholliday** [comment]
@bguyb It works for me.  Are you seeing any error messages in the generated document?

**Comment by bguyb** [comment]
> @bguyb It works for me. Are you seeing any error messages in the generated document?

I don't know. Where do I see errors?
The document opens up without showing errors.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
