### ISSUE TITLE
Excess enumeration of RowDfn.Cells property in SpreadsheetWriter.Write

### ISSUE THREAD

**Issue by george-polevoy** [OfficeDev/Open-Xml-PowerTools#64]
RowDfn.Cells is a IEnumerable, and during execution of the SpreadsheetWriter.Write method it's enumerated twice, causing excess memory usage and bugs in case of a stateful implementation of IEnumerable'1 interface.

For example, IEnumerable might use a database connection which might be disposed upon disposing the underlying IEnumerator.

**Comment by EricWhiteDev** [comment]
That is interesting - didn't remember writing that code to enumerate RowDfn.Cells twice.  Probably can insert a .ToList() that will take care of the issue.  I will be doing some maintenance in Open-Xml-PowerTools sometime this month, so will address this issue.

**Comment by george-polevoy** [comment]
You have a .Count() call.

In my JumboExcell framework i skip this count entirely and it works without the attribute, but i am not sure if that is compatible.

OpenXml standard should remove that, because it prohibits optimizations using the writers, like in this case.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
