### ISSUE TITLE
Converting Headers and Footers to HTML

### ISSUE THREAD

**Issue by rhuck** [OfficeDev/Open-Xml-PowerTools#66]
Hi, guys,

I'm trying to convert a docx file to an HTML document, and want a way to get the header and footer from the document, each in separate functions. Right now it looks like I can only get the body using the ConvertToHtml function and passing in the wDoc.

I don't seem to find a way to do this in Open-Xml-PowerTools. I think what would be best is if, in addition to passing in a WmlDocument or WordprocessingDocument object to ConvertToHtml, you could also open third method, passing in an XElement which could represent an XDocument root or even just a subset of the entire document.

Let me know if this makes sense, or if I missed some functionality in the library.

Thanks!

**Comment by EricWhiteDev** [comment]
Hi,

To convert headers/footers implies doing pagination on the document.  Pagination is not a feature of Open-Xml-PowerTools WmlToHtmlConverter.  I have thought about this feature, but it is a significant effort, and has not yet come to the top of the stack.

There are very specific semantics with regards to sections, headers, default headers, even and odd page headers, and headers that are inherited from the previous section.  It would be incorrect to display the incorrect headers for a section, so I deemed it necessary to defer this feature until some point in the future.

If you want to get HTML for headers, I suggest that you fabricate a temporary document where the main document part contains the content for the header.  Then convert that temporary document to HTML.

**Comment by rhuck** [comment]
Thank you for your response. Sorry for the delay.

I understand the complexity of the issue. Unfortunately what you suggest wouldn't work for my use case, as it's really for end-users to upload documents which could be viewed in an HTML format on their browser. I might have to implement a solution that would satisfy the most common and simple use, without support for more advanced features like you mentioned.

**Comment by penihel** [comment]
Something new about this? I need this feature too.

**Comment by EricWhiteDev** [comment]
@penihel No, no progress on this.  Writing a pagination routine (even an approximate one) is a multi-week project.  Waiting on someone who wants this enough to fund it.
