### ISSUE TITLE
Is it possible to get Page by page HTML for word document

### ISSUE THREAD

**Issue by pragneshmpatel** [OfficeDev/Open-Xml-PowerTools#67]
I am trying to extract html from docx file using power tools.  is there anyway to find pagebreaks in the document?

**Comment by EricWhiteDev** [comment]
No, that is not a feature of WmlToHtmlConverter.  Determining pagination would require implementation of a layout engine, and there is no layout engine in Open-Xml-PowerTools.

There are, in the document, w:lastRenderedPageBreak elements, however, you can't trust that they will be in the correct place.

Right now, there is no open source solution that can properly paginate an Open XML document.

**Comment by Will-Gregg** [comment]
This functionality is related to the request in #26 to be able to convert arbitrary OXML snippets to HTML.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
