### ISSUE TITLE
Line is not formatting in converted HTML

### ISSUE THREAD

**Issue by sara85sara** [OfficeDev/Open-Xml-PowerTools#71]
HI,
I am using this dll for converting my word document to HTML files. actually its converting but if there is any drawing line in my word document then the drawing line is not coming in converted html file. Is that bug or should i need to  add any code for that?
kindly let me know.

Thanks,

**Comment by EricWhiteDev** [comment]
@sara85sara No, this is not a feature of this module.  It would be nice to have, but requires extensive work, and I have not yet had time to address this.  It is not currently on the schedule.

**Comment by sara85sara** [comment]
Thanks a Eric,  I am able to meet all my requirements using our dll except the line <hr>  issue. It would be helpful if we add this feature.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
