### ISSUE TITLE
OpenXmlRegex.Replace Tabs Ignored

### ISSUE THREAD

**Issue by richard-jr-lewis** [OfficeDev/Open-Xml-PowerTools#78]
When calling OpenXmlRegex.Replace, it is failing to match text correctly when encountering special characters. In my case, I am trying to match against a whole word in a line that is spaced with tabs, but these are ignored by WmlSearchAndReplaceTransform.

`string contents = element.DescendantsTrimmed(W.txbxContent).Where(d => d.Name == W.t).Select(t => (string)t).StringConcatenate();`

Example: 

> TestWord1 _tab_ _tab_ TestWord2

Expected output: 

> TestWord1\t\tTestWord2

Actual output: 

> TestWord1TestWord2.

Is this something that could be investigated?

PS: I imagine similar may happen with other special characters

Thanks

**Comment by richard-jr-lewis** [comment]
Also appears to occur with line breaks

> < w:br />

**Comment by porkopek** [comment]
Which is your replacement string? Are you able to replace the content with a regex pattern? Like a capturing group? In my case, if I write "$1" in the replacement, I expect to get the first capture group, but I'm getting "$1" literal.

**Comment by richard-jr-lewis** [comment]
My issue occurs with how the Power Tools have trimmed the matching text, such that a standard regex string will not work. I did have some minor success with non-capturing groups and hardcoded text for it to look out for, but I ran in to other match issues. It then turns into a regex nightmare.

In regards to your issue with $1 and after reading through WmlSearchAndReplaceTransform, it appears to create a new run containing the "replacement" string. It is not designed to handle regex as part of the actual replacement string.

**Comment by ThomasBarnekow** [comment]
@richard-jr-lewis and @porkopek, I have just created a PR that enhances OpenXmlRegex to allow for replacement patterns. Previously, it simply replaced the matches with a fixed string.

I want to look into tabs and line breaks as well.
