### ISSUE TITLE
How to handle combine features

### ISSUE THREAD

**Issue by nandhu** [OfficeDev/Open-Xml-PowerTools#79]
Hi,
thanks for this excellent power tools.
I have one master document and 3 contributor documents. I want to combine all documents one by one and i want to see all changes. I need a feature in word application **Review > compare > combine**. I tried with word.interop its working fine. But I can't expose as service also i need to install word. I tried with both compare examples in power tools. but its not  solve my problem. is there any other option to combine word documents with revisions and accept and reject should work in word.

Thanks in advance.
@nanda

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
