### ISSUE TITLE
ChartUpdater output corrupt documents for Combo Charts

### ISSUE THREAD

**Issue by tugend** [OfficeDev/Open-Xml-PowerTools#82]
Given a word document with a single combo chart with a Line and an Area series outputs a corrupt    document. The ChartUpdater seems to have trouble with the notion of <c:ser>tags being nested in both <c:areaChart> and a <c:lineChart> tag block.

```
"We´re sorry. We can't open xxx.docx because we found a problem with its contents. Details: No   
error detail available".

ChartUpdater.UpdateChart(chartPart, new ChartData
{
    SeriesNames: new[] { "seriesone", "seriestwo" },
    CategoryNames: new[] { "category einz", "category twei", "category drei"},
    Values: new[]
    {
        Enumerable.Repeat(5d, 3).ToArray(),
        Enumerable.Repeat(8d, 3).ToArray(),
    })
});
```

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
