### ISSUE TITLE
DocumentFormat.OpenXml.dll V2.6.0.0 not having the publickeytoken

### ISSUE THREAD

**Issue by vdeo1** [OfficeDev/Open-Xml-PowerTools#83]
PS C:\Users\vaibhavd> [system.reflection.assembly]::loadfile("C:\Users\vaibhavd\AppData\Roaming\Skype\My Skype Received
Files\ConsoleApplication1\packages\OpenXMLSDK-MOT.2.6.0.0\lib\DocumentFormat.OpenXml.dll")
Exception calling "LoadFile" with "1" argument(s): "This assembly is built by a runtime newer than the currently loaded
 runtime and cannot be loaded. (Exception from HRESULT: 0x8013101B)"
At line:1 char:39
- [system.reflection.assembly]::loadfile <<<< ("C:\Users\vaibhavd\AppData\Roaming\Skype\My Skype Received Files\Console
  Application1\packages\OpenXMLSDK-MOT.2.6.0.0\lib\DocumentFormat.OpenXml.dll")
  - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  - FullyQualifiedErrorId : DotNetMethodException

**Comment by Will-Gregg** [comment]
Related to #9. With release of the SDK v2.7 DocumentFormat.OpenXml.Dll is strong named and has a public strong name key available. We will integrate this with PowerTools in the near future.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
