### ISSUE TITLE
text in front of <Repeat Select="..."/>

### ISSUE THREAD

**Issue by fynman** [OfficeDev/Open-Xml-PowerTools#85]
Dear,

  Is it possible to add text in front of a _Repeat Select_

  The text I'd like to generate, should look like:

text_in_front element_1 element2

Thanks,
Bart

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
