### ISSUE TITLE
HtmlToWmlConverter throws Duplicate attribute error

### ISSUE THREAD

**Issue by GarthMartin** [OfficeDev/Open-Xml-PowerTools#88]
I am trying to convert several HTML documents to WML and am getting the Duplicate attribute error in the `TransformToLower(XNode node)` method when I have a node that contains both lang and xml:lang attributes.  According to the XHTML spec, both attributes may appear.

Do I need to strip out one of the 2 in order for this to work properly?

Thanks

**Comment by EricWhiteDev** [comment]
@GarthMartin This may be a bug in the LINQ to XML library.  I have seen other bugs in the LtX lib with regards to duplicate attributes.  I have seen this in multi-threading scenarios.

I recommend striping out one of the two, and seeing if it works.
