### ISSUE TITLE
Issue with conversion of content in <dl><dd> tags

### ISSUE THREAD

**Issue by GarthMartin** [OfficeDev/Open-Xml-PowerTools#89]
When converting content in <dl><dd> tags the HTML converter appears to be adding a lot of extra linefeeds to the content of the elements.  For example the following HTML : 
`<dt>g. <strong>'double time'</strong></dt>
<dd>means twice (2) the straight-time hourly rate (<span lang='fr'>tarif double</span>),</dd>`

will get generated into WML like this:

g. 
'double time'
means twice (2) the straight-time hourly rate (
tarif double
),

and 
`<dt>a. <strong>'bargaining unit'</strong></dt>
<dd>means all the employees of the Employer in the Computer Systems Group, as described in the certificate issued by the former Public Service Staff Relations Board on the <time datetime='1969-03-11'>eleventh (11<sup>th</sup>) day of March 1969</time>, and as amended on <time datetime='1977-12-13'>December 13, 1977</time> and <time datetime='1999-06-01'>June 1, 1999</time> (<span lang='fr'>unité de négociation</span>),</dd>`

will be generated as:

a. 
'bargaining unit'
means all the employees of the Employer in the Computer Systems Group, as described in the certificate issued by the former Public Service Staff Relations Board on the 
eleventh (11
th
) day of March 1969
, and as amended on 
December 13, 1977
 and 
June 1, 1999
 (
unité de négociation
),

I have also discovered that a `<em>` element inside of a `<dd>` element will cause the WML to be corrupt and the file cannot be opened.  Example below:

`<dt>h. <strong>'employee'</strong></dt>
<dd>means a person so defined by the <em>Public Service Labour Relations Act</em> and who is a member of the bargaining unit (<span lang='fr'>employé</span>),</dd>`

I am not sure where to look in the OpenXmlPowerTools project to see what would need to be changed.

Thanks,

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
