### ISSUE TITLE
Issue merging documents

### ISSUE THREAD

**Issue by GarthMartin** [OfficeDev/Open-Xml-PowerTools#90]
I am getting a `Sequence contains no elements` error when trying to merge 2 documents.  One is a static docx and the other is a new document that was generated via the HtmlToWmlConverter.  It seems similar to this issue logged on openxmldeveloper.org before it was shut down.  

[http://openxmldeveloper.org/discussions/development_tools/f/17/p/7786/163270.aspx](http://openxmldeveloper.org/discussions/development_tools/f/17/p/7786/163270.aspx)

Any thoughts on this?

**Comment by GarthMartin** [comment]
I have narrowed this down to the merging of list styles in the 2 documents.  Our HTML has several list styles defined and when merged the style does not have a value on the w:nsid element which is throwing the error on line 1509 of DocumentBuilder.cs:

`  string abstractNSID = abstractElement
                            .Elements(W.nsid)
                            .First()
                            .Attribute(W.val)
                            .Value;`

If I look at the numbering.xml generated by the HtmlToWmlConverter I get the following:
`<w:abstractNum w:abstractNumId="0" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
    <w:multiLevelType w:val="multilevel" />
    <w:tmpl w:val="7D26959A" />
    <w:lvl w:ilvl="0">....`

But in a normal Word generated file I get the following:

`<w:abstractNum w:abstractNumId="0">
    <w:nsid w:val="187F7A9D"/>
    <w:multiLevelType w:val="hybridMultilevel"/>
    <w:tmpl w:val="7C1CAFEC"/>
    <w:lvl w:ilvl="0" w:tplc="10090001">`

Note the added w:nsid node that the PowerTools generated one does not have.

I am not comfortable enough with this library to begin a pull request, but I assume the fix would have to be in the Html Converter?  What value should be in the w:nsid node?

Any help would be appreciated.  

Garth

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
