### ISSUE TITLE
Some cells are removed when accepting revisions although the document has no revisions

### ISSUE THREAD

**Issue by michel49** [OfficeDev/Open-Xml-PowerTools#93]
I' using Open-Xml-PowerTools-vNext (4.3) and more specifically RevisionAccepter.cs (version 2.6.00) coupled with Open-XML-SDK-vNext (2.6.1) under Mono 4.2 SR2 (4.2.3.4).
Although the document has no revisions to accept some cells are removed when running AcceptRevisions on it.
I have attached the document before accepting revisions [EFR.docx](https://github.com/OfficeDev/Open-Xml-PowerTools/files/484355/EFR.docx) and the processed document after accepting revisions [EFR.docx](https://github.com/OfficeDev/Open-Xml-PowerTools/files/484363/EFR.docx).
The problem seems to be related to the funtion RemoveRowsLeftEmptyByMoveFrom().

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
