### ISSUE TITLE
The referenced assembly 'OpenXmlPowerTools, Version=4.2.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name. 

### ISSUE THREAD

**Issue by felixcen** [OfficeDev/Open-Xml-PowerTools#94]
Hi, 

We are trying to use the package from nuget, but we are getting the strong name error. Could you please provide a signed version of it? 

Thanks,

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
