### ISSUE TITLE
DocumentBuilder using InsertId does not support inserting into Headers/Footers

### ISSUE THREAD

**Issue by koyote** [OfficeDev/Open-Xml-PowerTools#95]
When using the DocumentBuilder in conjuction with the InsertId option the insertion into Headers and/or Footers is not supported.

Is this something that is planned to be support at some point?

**Comment by juanperezADD** [comment]
Any news?

**Comment by EricWhiteDev** [comment]
Yes, this is work that is scheduled.  I anticipate that this work will be completed sometime within the next month.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
