### ISSUE TITLE
WmlToHtml Input string was not in a correct format.

### ISSUE THREAD

**Issue by astromediaonly** [OfficeDev/Open-Xml-PowerTools#98]
Hi, im trying to convert word document to html but HtmlConverter.ConvertToHtml failing on "Input string was not in a correct format." exception. Is it bug or is there some way hot to avoid that?

[stackTrace.txt](https://github.com/OfficeDev/Open-Xml-PowerTools/files/581280/stackTrace.txt)

NuGet:
DocumentFormat.OpenXml         2.5                          
OpenXmlPowerTools              4.5.3.0

**Comment by Will-Gregg** [comment]
@astromediaonly would it be possible for you to provide the source document in order to try and debug this more thoroughly?

**Comment by astromediaonly** [comment]
[Принт договор.docx](https://github.com/OfficeDev/Open-Xml-PowerTools/files/782647/default.docx)

@Will-Gregg this one is throwing that exception, hope it helps ... i have almost forgot after that much time :)

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
