### ISSUE TITLE
SpreadsheetWriter with multiple sheets produces invalid output

### ISSUE THREAD

**Issue by ocdi** [OfficeDev/Open-Xml-PowerTools#99]
I'm trying to produce a workbook that contains multiple sheets. This works, however I get an error when loading using Excel 2016 "We found a problem with some content". The recovery appears to have all the contents, but the error is confusing to users who would receive these files.

This is my test case that generates this. Am I doing something wrong or is creating multiple sheets like this not supported?

```C#
            var file = Path.Combine(Path.GetTempPath(), $"testManual{Guid.NewGuid()}.xlsx");
            SpreadsheetWriter.Write(file, new WorkbookDfn
            {
                Worksheets = new[] {
                    new WorksheetDfn {
                        ColumnHeadings = new[] { new CellDfn { Value = "Col1" }, new CellDfn { Value = "Col2" }  },
                        Name = "First",
                        TableName = "FirstTable",
                        Rows = new [] {
                            new RowDfn { Cells = new [] { new CellDfn { Value="Row1Col1" }, new CellDfn { Value="Row1Col2" } } },
                            new RowDfn { Cells = new [] { new CellDfn { Value= "Row2Col1" }, new CellDfn { Value= "Row2Col2" } } }
                        }
                    },
                    new WorksheetDfn {
                        ColumnHeadings = new[] { new CellDfn { Value = "Col1" }, new CellDfn { Value = "Col2" }  },
                        Name = "Second",
                        TableName = "SecondTable",
                        Rows = new [] {
                            new RowDfn { Cells = new [] { new CellDfn { Value="Sheet2Row1Col1" }, new CellDfn { Value= "Sheet2Row1Col2" } } },
                            new RowDfn { Cells = new [] { new CellDfn { Value= "Sheet2Row2Col1" }, new CellDfn { Value= "Sheet2Row2Col2" } } }
                        }
                    }
                }
            });
```
[testManual6180587b-ff81-4f7b-8a25-832be10f3a8a.xlsx](https://github.com/OfficeDev/Open-Xml-PowerTools/files/621041/testManual6180587b-ff81-4f7b-8a25-832be10f3a8a.xlsx)

**Comment by ocdi** [comment]
I just observed that Excel appears to be complaining about the Tables:

`Repaired Records: Table from /xl/tables/table2.xml part (Table)`

I just had the realisation that the by not specifying a TableName it seems to work OK. Not sure if this is a bug or just not intended, however Excel does seem to be able to have multiple tables in it so I suspect this should be supported. In the short term I can not set the TableName to prevent the warning/error.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
